// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_cs_message.proto

package com.caidt.proto;

public final class ProtoCsMessage {
  private ProtoCsMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CsMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.caidt.proto.CsMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
     */
    boolean hasLoginRequest();
    /**
     * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
     */
    com.caidt.proto.ProtoDescriptor.LoginRequest getLoginRequest();
    /**
     * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
     */
    com.caidt.proto.ProtoDescriptor.LoginRequestOrBuilder getLoginRequestOrBuilder();

    /**
     * <pre>
     *        GetPlayerInfoRequest getPlayerInfoRequest = 102;
     * </pre>
     *
     * <code>optional .com.caidt.proto.GetAllActivityRequest getAllActivityRequest = 103;</code>
     */
    boolean hasGetAllActivityRequest();
    /**
     * <pre>
     *        GetPlayerInfoRequest getPlayerInfoRequest = 102;
     * </pre>
     *
     * <code>optional .com.caidt.proto.GetAllActivityRequest getAllActivityRequest = 103;</code>
     */
    com.caidt.proto.ProtoActivity.GetAllActivityRequest getGetAllActivityRequest();
    /**
     * <pre>
     *        GetPlayerInfoRequest getPlayerInfoRequest = 102;
     * </pre>
     *
     * <code>optional .com.caidt.proto.GetAllActivityRequest getAllActivityRequest = 103;</code>
     */
    com.caidt.proto.ProtoActivity.GetAllActivityRequestOrBuilder getGetAllActivityRequestOrBuilder();

    /**
     * <code>optional .com.caidt.proto.GetActivityRequest getActivityRequest = 104;</code>
     */
    boolean hasGetActivityRequest();
    /**
     * <code>optional .com.caidt.proto.GetActivityRequest getActivityRequest = 104;</code>
     */
    com.caidt.proto.ProtoActivity.GetActivityRequest getGetActivityRequest();
    /**
     * <code>optional .com.caidt.proto.GetActivityRequest getActivityRequest = 104;</code>
     */
    com.caidt.proto.ProtoActivity.GetActivityRequestOrBuilder getGetActivityRequestOrBuilder();

    public com.caidt.proto.ProtoCsMessage.CsMessage.CmdCase getCmdCase();
  }
  /**
   * Protobuf type {@code com.caidt.proto.CsMessage}
   */
  public  static final class CsMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.caidt.proto.CsMessage)
      CsMessageOrBuilder {
    // Use CsMessage.newBuilder() to construct.
    private CsMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CsMessage() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CsMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 810: {
              com.caidt.proto.ProtoDescriptor.LoginRequest.Builder subBuilder = null;
              if (cmdCase_ == 101) {
                subBuilder = ((com.caidt.proto.ProtoDescriptor.LoginRequest) cmd_).toBuilder();
              }
              cmd_ =
                  input.readMessage(com.caidt.proto.ProtoDescriptor.LoginRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.caidt.proto.ProtoDescriptor.LoginRequest) cmd_);
                cmd_ = subBuilder.buildPartial();
              }
              cmdCase_ = 101;
              break;
            }
            case 826: {
              com.caidt.proto.ProtoActivity.GetAllActivityRequest.Builder subBuilder = null;
              if (cmdCase_ == 103) {
                subBuilder = ((com.caidt.proto.ProtoActivity.GetAllActivityRequest) cmd_).toBuilder();
              }
              cmd_ =
                  input.readMessage(com.caidt.proto.ProtoActivity.GetAllActivityRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.caidt.proto.ProtoActivity.GetAllActivityRequest) cmd_);
                cmd_ = subBuilder.buildPartial();
              }
              cmdCase_ = 103;
              break;
            }
            case 834: {
              com.caidt.proto.ProtoActivity.GetActivityRequest.Builder subBuilder = null;
              if (cmdCase_ == 104) {
                subBuilder = ((com.caidt.proto.ProtoActivity.GetActivityRequest) cmd_).toBuilder();
              }
              cmd_ =
                  input.readMessage(com.caidt.proto.ProtoActivity.GetActivityRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.caidt.proto.ProtoActivity.GetActivityRequest) cmd_);
                cmd_ = subBuilder.buildPartial();
              }
              cmdCase_ = 104;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.caidt.proto.ProtoCsMessage.internal_static_com_caidt_proto_CsMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.caidt.proto.ProtoCsMessage.internal_static_com_caidt_proto_CsMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.caidt.proto.ProtoCsMessage.CsMessage.class, com.caidt.proto.ProtoCsMessage.CsMessage.Builder.class);
    }

    private int bitField0_;
    private int cmdCase_ = 0;
    private java.lang.Object cmd_;
    public enum CmdCase
        implements com.google.protobuf.Internal.EnumLite {
      LOGINREQUEST(101),
      GETALLACTIVITYREQUEST(103),
      GETACTIVITYREQUEST(104),
      CMD_NOT_SET(0);
      private final int value;
      private CmdCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static CmdCase valueOf(int value) {
        return forNumber(value);
      }

      public static CmdCase forNumber(int value) {
        switch (value) {
          case 101: return LOGINREQUEST;
          case 103: return GETALLACTIVITYREQUEST;
          case 104: return GETACTIVITYREQUEST;
          case 0: return CMD_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public CmdCase
    getCmdCase() {
      return CmdCase.forNumber(
          cmdCase_);
    }

    public static final int LOGINREQUEST_FIELD_NUMBER = 101;
    /**
     * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
     */
    public boolean hasLoginRequest() {
      return cmdCase_ == 101;
    }
    /**
     * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
     */
    public com.caidt.proto.ProtoDescriptor.LoginRequest getLoginRequest() {
      if (cmdCase_ == 101) {
         return (com.caidt.proto.ProtoDescriptor.LoginRequest) cmd_;
      }
      return com.caidt.proto.ProtoDescriptor.LoginRequest.getDefaultInstance();
    }
    /**
     * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
     */
    public com.caidt.proto.ProtoDescriptor.LoginRequestOrBuilder getLoginRequestOrBuilder() {
      if (cmdCase_ == 101) {
         return (com.caidt.proto.ProtoDescriptor.LoginRequest) cmd_;
      }
      return com.caidt.proto.ProtoDescriptor.LoginRequest.getDefaultInstance();
    }

    public static final int GETALLACTIVITYREQUEST_FIELD_NUMBER = 103;
    /**
     * <pre>
     *        GetPlayerInfoRequest getPlayerInfoRequest = 102;
     * </pre>
     *
     * <code>optional .com.caidt.proto.GetAllActivityRequest getAllActivityRequest = 103;</code>
     */
    public boolean hasGetAllActivityRequest() {
      return cmdCase_ == 103;
    }
    /**
     * <pre>
     *        GetPlayerInfoRequest getPlayerInfoRequest = 102;
     * </pre>
     *
     * <code>optional .com.caidt.proto.GetAllActivityRequest getAllActivityRequest = 103;</code>
     */
    public com.caidt.proto.ProtoActivity.GetAllActivityRequest getGetAllActivityRequest() {
      if (cmdCase_ == 103) {
         return (com.caidt.proto.ProtoActivity.GetAllActivityRequest) cmd_;
      }
      return com.caidt.proto.ProtoActivity.GetAllActivityRequest.getDefaultInstance();
    }
    /**
     * <pre>
     *        GetPlayerInfoRequest getPlayerInfoRequest = 102;
     * </pre>
     *
     * <code>optional .com.caidt.proto.GetAllActivityRequest getAllActivityRequest = 103;</code>
     */
    public com.caidt.proto.ProtoActivity.GetAllActivityRequestOrBuilder getGetAllActivityRequestOrBuilder() {
      if (cmdCase_ == 103) {
         return (com.caidt.proto.ProtoActivity.GetAllActivityRequest) cmd_;
      }
      return com.caidt.proto.ProtoActivity.GetAllActivityRequest.getDefaultInstance();
    }

    public static final int GETACTIVITYREQUEST_FIELD_NUMBER = 104;
    /**
     * <code>optional .com.caidt.proto.GetActivityRequest getActivityRequest = 104;</code>
     */
    public boolean hasGetActivityRequest() {
      return cmdCase_ == 104;
    }
    /**
     * <code>optional .com.caidt.proto.GetActivityRequest getActivityRequest = 104;</code>
     */
    public com.caidt.proto.ProtoActivity.GetActivityRequest getGetActivityRequest() {
      if (cmdCase_ == 104) {
         return (com.caidt.proto.ProtoActivity.GetActivityRequest) cmd_;
      }
      return com.caidt.proto.ProtoActivity.GetActivityRequest.getDefaultInstance();
    }
    /**
     * <code>optional .com.caidt.proto.GetActivityRequest getActivityRequest = 104;</code>
     */
    public com.caidt.proto.ProtoActivity.GetActivityRequestOrBuilder getGetActivityRequestOrBuilder() {
      if (cmdCase_ == 104) {
         return (com.caidt.proto.ProtoActivity.GetActivityRequest) cmd_;
      }
      return com.caidt.proto.ProtoActivity.GetActivityRequest.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasLoginRequest()) {
        if (!getLoginRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasGetActivityRequest()) {
        if (!getGetActivityRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmdCase_ == 101) {
        output.writeMessage(101, (com.caidt.proto.ProtoDescriptor.LoginRequest) cmd_);
      }
      if (cmdCase_ == 103) {
        output.writeMessage(103, (com.caidt.proto.ProtoActivity.GetAllActivityRequest) cmd_);
      }
      if (cmdCase_ == 104) {
        output.writeMessage(104, (com.caidt.proto.ProtoActivity.GetActivityRequest) cmd_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmdCase_ == 101) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(101, (com.caidt.proto.ProtoDescriptor.LoginRequest) cmd_);
      }
      if (cmdCase_ == 103) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(103, (com.caidt.proto.ProtoActivity.GetAllActivityRequest) cmd_);
      }
      if (cmdCase_ == 104) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(104, (com.caidt.proto.ProtoActivity.GetActivityRequest) cmd_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.caidt.proto.ProtoCsMessage.CsMessage)) {
        return super.equals(obj);
      }
      com.caidt.proto.ProtoCsMessage.CsMessage other = (com.caidt.proto.ProtoCsMessage.CsMessage) obj;

      boolean result = true;
      result = result && getCmdCase().equals(
          other.getCmdCase());
      if (!result) return false;
      switch (cmdCase_) {
        case 101:
          result = result && getLoginRequest()
              .equals(other.getLoginRequest());
          break;
        case 103:
          result = result && getGetAllActivityRequest()
              .equals(other.getGetAllActivityRequest());
          break;
        case 104:
          result = result && getGetActivityRequest()
              .equals(other.getGetActivityRequest());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      switch (cmdCase_) {
        case 101:
          hash = (37 * hash) + LOGINREQUEST_FIELD_NUMBER;
          hash = (53 * hash) + getLoginRequest().hashCode();
          break;
        case 103:
          hash = (37 * hash) + GETALLACTIVITYREQUEST_FIELD_NUMBER;
          hash = (53 * hash) + getGetAllActivityRequest().hashCode();
          break;
        case 104:
          hash = (37 * hash) + GETACTIVITYREQUEST_FIELD_NUMBER;
          hash = (53 * hash) + getGetActivityRequest().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.caidt.proto.ProtoCsMessage.CsMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caidt.proto.ProtoCsMessage.CsMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caidt.proto.ProtoCsMessage.CsMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caidt.proto.ProtoCsMessage.CsMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caidt.proto.ProtoCsMessage.CsMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.caidt.proto.ProtoCsMessage.CsMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.caidt.proto.ProtoCsMessage.CsMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.caidt.proto.ProtoCsMessage.CsMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.caidt.proto.ProtoCsMessage.CsMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.caidt.proto.ProtoCsMessage.CsMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.caidt.proto.ProtoCsMessage.CsMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.caidt.proto.CsMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.caidt.proto.CsMessage)
        com.caidt.proto.ProtoCsMessage.CsMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.caidt.proto.ProtoCsMessage.internal_static_com_caidt_proto_CsMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.caidt.proto.ProtoCsMessage.internal_static_com_caidt_proto_CsMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.caidt.proto.ProtoCsMessage.CsMessage.class, com.caidt.proto.ProtoCsMessage.CsMessage.Builder.class);
      }

      // Construct using com.caidt.proto.ProtoCsMessage.CsMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        cmdCase_ = 0;
        cmd_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.caidt.proto.ProtoCsMessage.internal_static_com_caidt_proto_CsMessage_descriptor;
      }

      public com.caidt.proto.ProtoCsMessage.CsMessage getDefaultInstanceForType() {
        return com.caidt.proto.ProtoCsMessage.CsMessage.getDefaultInstance();
      }

      public com.caidt.proto.ProtoCsMessage.CsMessage build() {
        com.caidt.proto.ProtoCsMessage.CsMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.caidt.proto.ProtoCsMessage.CsMessage buildPartial() {
        com.caidt.proto.ProtoCsMessage.CsMessage result = new com.caidt.proto.ProtoCsMessage.CsMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (cmdCase_ == 101) {
          if (loginRequestBuilder_ == null) {
            result.cmd_ = cmd_;
          } else {
            result.cmd_ = loginRequestBuilder_.build();
          }
        }
        if (cmdCase_ == 103) {
          if (getAllActivityRequestBuilder_ == null) {
            result.cmd_ = cmd_;
          } else {
            result.cmd_ = getAllActivityRequestBuilder_.build();
          }
        }
        if (cmdCase_ == 104) {
          if (getActivityRequestBuilder_ == null) {
            result.cmd_ = cmd_;
          } else {
            result.cmd_ = getActivityRequestBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.cmdCase_ = cmdCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.caidt.proto.ProtoCsMessage.CsMessage) {
          return mergeFrom((com.caidt.proto.ProtoCsMessage.CsMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.caidt.proto.ProtoCsMessage.CsMessage other) {
        if (other == com.caidt.proto.ProtoCsMessage.CsMessage.getDefaultInstance()) return this;
        switch (other.getCmdCase()) {
          case LOGINREQUEST: {
            mergeLoginRequest(other.getLoginRequest());
            break;
          }
          case GETALLACTIVITYREQUEST: {
            mergeGetAllActivityRequest(other.getGetAllActivityRequest());
            break;
          }
          case GETACTIVITYREQUEST: {
            mergeGetActivityRequest(other.getGetActivityRequest());
            break;
          }
          case CMD_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (hasLoginRequest()) {
          if (!getLoginRequest().isInitialized()) {
            return false;
          }
        }
        if (hasGetActivityRequest()) {
          if (!getGetActivityRequest().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.caidt.proto.ProtoCsMessage.CsMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.caidt.proto.ProtoCsMessage.CsMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int cmdCase_ = 0;
      private java.lang.Object cmd_;
      public CmdCase
          getCmdCase() {
        return CmdCase.forNumber(
            cmdCase_);
      }

      public Builder clearCmd() {
        cmdCase_ = 0;
        cmd_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilderV3<
          com.caidt.proto.ProtoDescriptor.LoginRequest, com.caidt.proto.ProtoDescriptor.LoginRequest.Builder, com.caidt.proto.ProtoDescriptor.LoginRequestOrBuilder> loginRequestBuilder_;
      /**
       * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
       */
      public boolean hasLoginRequest() {
        return cmdCase_ == 101;
      }
      /**
       * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
       */
      public com.caidt.proto.ProtoDescriptor.LoginRequest getLoginRequest() {
        if (loginRequestBuilder_ == null) {
          if (cmdCase_ == 101) {
            return (com.caidt.proto.ProtoDescriptor.LoginRequest) cmd_;
          }
          return com.caidt.proto.ProtoDescriptor.LoginRequest.getDefaultInstance();
        } else {
          if (cmdCase_ == 101) {
            return loginRequestBuilder_.getMessage();
          }
          return com.caidt.proto.ProtoDescriptor.LoginRequest.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
       */
      public Builder setLoginRequest(com.caidt.proto.ProtoDescriptor.LoginRequest value) {
        if (loginRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cmd_ = value;
          onChanged();
        } else {
          loginRequestBuilder_.setMessage(value);
        }
        cmdCase_ = 101;
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
       */
      public Builder setLoginRequest(
          com.caidt.proto.ProtoDescriptor.LoginRequest.Builder builderForValue) {
        if (loginRequestBuilder_ == null) {
          cmd_ = builderForValue.build();
          onChanged();
        } else {
          loginRequestBuilder_.setMessage(builderForValue.build());
        }
        cmdCase_ = 101;
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
       */
      public Builder mergeLoginRequest(com.caidt.proto.ProtoDescriptor.LoginRequest value) {
        if (loginRequestBuilder_ == null) {
          if (cmdCase_ == 101 &&
              cmd_ != com.caidt.proto.ProtoDescriptor.LoginRequest.getDefaultInstance()) {
            cmd_ = com.caidt.proto.ProtoDescriptor.LoginRequest.newBuilder((com.caidt.proto.ProtoDescriptor.LoginRequest) cmd_)
                .mergeFrom(value).buildPartial();
          } else {
            cmd_ = value;
          }
          onChanged();
        } else {
          if (cmdCase_ == 101) {
            loginRequestBuilder_.mergeFrom(value);
          }
          loginRequestBuilder_.setMessage(value);
        }
        cmdCase_ = 101;
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
       */
      public Builder clearLoginRequest() {
        if (loginRequestBuilder_ == null) {
          if (cmdCase_ == 101) {
            cmdCase_ = 0;
            cmd_ = null;
            onChanged();
          }
        } else {
          if (cmdCase_ == 101) {
            cmdCase_ = 0;
            cmd_ = null;
          }
          loginRequestBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
       */
      public com.caidt.proto.ProtoDescriptor.LoginRequest.Builder getLoginRequestBuilder() {
        return getLoginRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
       */
      public com.caidt.proto.ProtoDescriptor.LoginRequestOrBuilder getLoginRequestOrBuilder() {
        if ((cmdCase_ == 101) && (loginRequestBuilder_ != null)) {
          return loginRequestBuilder_.getMessageOrBuilder();
        } else {
          if (cmdCase_ == 101) {
            return (com.caidt.proto.ProtoDescriptor.LoginRequest) cmd_;
          }
          return com.caidt.proto.ProtoDescriptor.LoginRequest.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.caidt.proto.ProtoDescriptor.LoginRequest, com.caidt.proto.ProtoDescriptor.LoginRequest.Builder, com.caidt.proto.ProtoDescriptor.LoginRequestOrBuilder> 
          getLoginRequestFieldBuilder() {
        if (loginRequestBuilder_ == null) {
          if (!(cmdCase_ == 101)) {
            cmd_ = com.caidt.proto.ProtoDescriptor.LoginRequest.getDefaultInstance();
          }
          loginRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.caidt.proto.ProtoDescriptor.LoginRequest, com.caidt.proto.ProtoDescriptor.LoginRequest.Builder, com.caidt.proto.ProtoDescriptor.LoginRequestOrBuilder>(
                  (com.caidt.proto.ProtoDescriptor.LoginRequest) cmd_,
                  getParentForChildren(),
                  isClean());
          cmd_ = null;
        }
        cmdCase_ = 101;
        onChanged();;
        return loginRequestBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.caidt.proto.ProtoActivity.GetAllActivityRequest, com.caidt.proto.ProtoActivity.GetAllActivityRequest.Builder, com.caidt.proto.ProtoActivity.GetAllActivityRequestOrBuilder> getAllActivityRequestBuilder_;
      /**
       * <pre>
       *        GetPlayerInfoRequest getPlayerInfoRequest = 102;
       * </pre>
       *
       * <code>optional .com.caidt.proto.GetAllActivityRequest getAllActivityRequest = 103;</code>
       */
      public boolean hasGetAllActivityRequest() {
        return cmdCase_ == 103;
      }
      /**
       * <pre>
       *        GetPlayerInfoRequest getPlayerInfoRequest = 102;
       * </pre>
       *
       * <code>optional .com.caidt.proto.GetAllActivityRequest getAllActivityRequest = 103;</code>
       */
      public com.caidt.proto.ProtoActivity.GetAllActivityRequest getGetAllActivityRequest() {
        if (getAllActivityRequestBuilder_ == null) {
          if (cmdCase_ == 103) {
            return (com.caidt.proto.ProtoActivity.GetAllActivityRequest) cmd_;
          }
          return com.caidt.proto.ProtoActivity.GetAllActivityRequest.getDefaultInstance();
        } else {
          if (cmdCase_ == 103) {
            return getAllActivityRequestBuilder_.getMessage();
          }
          return com.caidt.proto.ProtoActivity.GetAllActivityRequest.getDefaultInstance();
        }
      }
      /**
       * <pre>
       *        GetPlayerInfoRequest getPlayerInfoRequest = 102;
       * </pre>
       *
       * <code>optional .com.caidt.proto.GetAllActivityRequest getAllActivityRequest = 103;</code>
       */
      public Builder setGetAllActivityRequest(com.caidt.proto.ProtoActivity.GetAllActivityRequest value) {
        if (getAllActivityRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cmd_ = value;
          onChanged();
        } else {
          getAllActivityRequestBuilder_.setMessage(value);
        }
        cmdCase_ = 103;
        return this;
      }
      /**
       * <pre>
       *        GetPlayerInfoRequest getPlayerInfoRequest = 102;
       * </pre>
       *
       * <code>optional .com.caidt.proto.GetAllActivityRequest getAllActivityRequest = 103;</code>
       */
      public Builder setGetAllActivityRequest(
          com.caidt.proto.ProtoActivity.GetAllActivityRequest.Builder builderForValue) {
        if (getAllActivityRequestBuilder_ == null) {
          cmd_ = builderForValue.build();
          onChanged();
        } else {
          getAllActivityRequestBuilder_.setMessage(builderForValue.build());
        }
        cmdCase_ = 103;
        return this;
      }
      /**
       * <pre>
       *        GetPlayerInfoRequest getPlayerInfoRequest = 102;
       * </pre>
       *
       * <code>optional .com.caidt.proto.GetAllActivityRequest getAllActivityRequest = 103;</code>
       */
      public Builder mergeGetAllActivityRequest(com.caidt.proto.ProtoActivity.GetAllActivityRequest value) {
        if (getAllActivityRequestBuilder_ == null) {
          if (cmdCase_ == 103 &&
              cmd_ != com.caidt.proto.ProtoActivity.GetAllActivityRequest.getDefaultInstance()) {
            cmd_ = com.caidt.proto.ProtoActivity.GetAllActivityRequest.newBuilder((com.caidt.proto.ProtoActivity.GetAllActivityRequest) cmd_)
                .mergeFrom(value).buildPartial();
          } else {
            cmd_ = value;
          }
          onChanged();
        } else {
          if (cmdCase_ == 103) {
            getAllActivityRequestBuilder_.mergeFrom(value);
          }
          getAllActivityRequestBuilder_.setMessage(value);
        }
        cmdCase_ = 103;
        return this;
      }
      /**
       * <pre>
       *        GetPlayerInfoRequest getPlayerInfoRequest = 102;
       * </pre>
       *
       * <code>optional .com.caidt.proto.GetAllActivityRequest getAllActivityRequest = 103;</code>
       */
      public Builder clearGetAllActivityRequest() {
        if (getAllActivityRequestBuilder_ == null) {
          if (cmdCase_ == 103) {
            cmdCase_ = 0;
            cmd_ = null;
            onChanged();
          }
        } else {
          if (cmdCase_ == 103) {
            cmdCase_ = 0;
            cmd_ = null;
          }
          getAllActivityRequestBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *        GetPlayerInfoRequest getPlayerInfoRequest = 102;
       * </pre>
       *
       * <code>optional .com.caidt.proto.GetAllActivityRequest getAllActivityRequest = 103;</code>
       */
      public com.caidt.proto.ProtoActivity.GetAllActivityRequest.Builder getGetAllActivityRequestBuilder() {
        return getGetAllActivityRequestFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *        GetPlayerInfoRequest getPlayerInfoRequest = 102;
       * </pre>
       *
       * <code>optional .com.caidt.proto.GetAllActivityRequest getAllActivityRequest = 103;</code>
       */
      public com.caidt.proto.ProtoActivity.GetAllActivityRequestOrBuilder getGetAllActivityRequestOrBuilder() {
        if ((cmdCase_ == 103) && (getAllActivityRequestBuilder_ != null)) {
          return getAllActivityRequestBuilder_.getMessageOrBuilder();
        } else {
          if (cmdCase_ == 103) {
            return (com.caidt.proto.ProtoActivity.GetAllActivityRequest) cmd_;
          }
          return com.caidt.proto.ProtoActivity.GetAllActivityRequest.getDefaultInstance();
        }
      }
      /**
       * <pre>
       *        GetPlayerInfoRequest getPlayerInfoRequest = 102;
       * </pre>
       *
       * <code>optional .com.caidt.proto.GetAllActivityRequest getAllActivityRequest = 103;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.caidt.proto.ProtoActivity.GetAllActivityRequest, com.caidt.proto.ProtoActivity.GetAllActivityRequest.Builder, com.caidt.proto.ProtoActivity.GetAllActivityRequestOrBuilder> 
          getGetAllActivityRequestFieldBuilder() {
        if (getAllActivityRequestBuilder_ == null) {
          if (!(cmdCase_ == 103)) {
            cmd_ = com.caidt.proto.ProtoActivity.GetAllActivityRequest.getDefaultInstance();
          }
          getAllActivityRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.caidt.proto.ProtoActivity.GetAllActivityRequest, com.caidt.proto.ProtoActivity.GetAllActivityRequest.Builder, com.caidt.proto.ProtoActivity.GetAllActivityRequestOrBuilder>(
                  (com.caidt.proto.ProtoActivity.GetAllActivityRequest) cmd_,
                  getParentForChildren(),
                  isClean());
          cmd_ = null;
        }
        cmdCase_ = 103;
        onChanged();;
        return getAllActivityRequestBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.caidt.proto.ProtoActivity.GetActivityRequest, com.caidt.proto.ProtoActivity.GetActivityRequest.Builder, com.caidt.proto.ProtoActivity.GetActivityRequestOrBuilder> getActivityRequestBuilder_;
      /**
       * <code>optional .com.caidt.proto.GetActivityRequest getActivityRequest = 104;</code>
       */
      public boolean hasGetActivityRequest() {
        return cmdCase_ == 104;
      }
      /**
       * <code>optional .com.caidt.proto.GetActivityRequest getActivityRequest = 104;</code>
       */
      public com.caidt.proto.ProtoActivity.GetActivityRequest getGetActivityRequest() {
        if (getActivityRequestBuilder_ == null) {
          if (cmdCase_ == 104) {
            return (com.caidt.proto.ProtoActivity.GetActivityRequest) cmd_;
          }
          return com.caidt.proto.ProtoActivity.GetActivityRequest.getDefaultInstance();
        } else {
          if (cmdCase_ == 104) {
            return getActivityRequestBuilder_.getMessage();
          }
          return com.caidt.proto.ProtoActivity.GetActivityRequest.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.caidt.proto.GetActivityRequest getActivityRequest = 104;</code>
       */
      public Builder setGetActivityRequest(com.caidt.proto.ProtoActivity.GetActivityRequest value) {
        if (getActivityRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cmd_ = value;
          onChanged();
        } else {
          getActivityRequestBuilder_.setMessage(value);
        }
        cmdCase_ = 104;
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.GetActivityRequest getActivityRequest = 104;</code>
       */
      public Builder setGetActivityRequest(
          com.caidt.proto.ProtoActivity.GetActivityRequest.Builder builderForValue) {
        if (getActivityRequestBuilder_ == null) {
          cmd_ = builderForValue.build();
          onChanged();
        } else {
          getActivityRequestBuilder_.setMessage(builderForValue.build());
        }
        cmdCase_ = 104;
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.GetActivityRequest getActivityRequest = 104;</code>
       */
      public Builder mergeGetActivityRequest(com.caidt.proto.ProtoActivity.GetActivityRequest value) {
        if (getActivityRequestBuilder_ == null) {
          if (cmdCase_ == 104 &&
              cmd_ != com.caidt.proto.ProtoActivity.GetActivityRequest.getDefaultInstance()) {
            cmd_ = com.caidt.proto.ProtoActivity.GetActivityRequest.newBuilder((com.caidt.proto.ProtoActivity.GetActivityRequest) cmd_)
                .mergeFrom(value).buildPartial();
          } else {
            cmd_ = value;
          }
          onChanged();
        } else {
          if (cmdCase_ == 104) {
            getActivityRequestBuilder_.mergeFrom(value);
          }
          getActivityRequestBuilder_.setMessage(value);
        }
        cmdCase_ = 104;
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.GetActivityRequest getActivityRequest = 104;</code>
       */
      public Builder clearGetActivityRequest() {
        if (getActivityRequestBuilder_ == null) {
          if (cmdCase_ == 104) {
            cmdCase_ = 0;
            cmd_ = null;
            onChanged();
          }
        } else {
          if (cmdCase_ == 104) {
            cmdCase_ = 0;
            cmd_ = null;
          }
          getActivityRequestBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.GetActivityRequest getActivityRequest = 104;</code>
       */
      public com.caidt.proto.ProtoActivity.GetActivityRequest.Builder getGetActivityRequestBuilder() {
        return getGetActivityRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.caidt.proto.GetActivityRequest getActivityRequest = 104;</code>
       */
      public com.caidt.proto.ProtoActivity.GetActivityRequestOrBuilder getGetActivityRequestOrBuilder() {
        if ((cmdCase_ == 104) && (getActivityRequestBuilder_ != null)) {
          return getActivityRequestBuilder_.getMessageOrBuilder();
        } else {
          if (cmdCase_ == 104) {
            return (com.caidt.proto.ProtoActivity.GetActivityRequest) cmd_;
          }
          return com.caidt.proto.ProtoActivity.GetActivityRequest.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.caidt.proto.GetActivityRequest getActivityRequest = 104;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.caidt.proto.ProtoActivity.GetActivityRequest, com.caidt.proto.ProtoActivity.GetActivityRequest.Builder, com.caidt.proto.ProtoActivity.GetActivityRequestOrBuilder> 
          getGetActivityRequestFieldBuilder() {
        if (getActivityRequestBuilder_ == null) {
          if (!(cmdCase_ == 104)) {
            cmd_ = com.caidt.proto.ProtoActivity.GetActivityRequest.getDefaultInstance();
          }
          getActivityRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.caidt.proto.ProtoActivity.GetActivityRequest, com.caidt.proto.ProtoActivity.GetActivityRequest.Builder, com.caidt.proto.ProtoActivity.GetActivityRequestOrBuilder>(
                  (com.caidt.proto.ProtoActivity.GetActivityRequest) cmd_,
                  getParentForChildren(),
                  isClean());
          cmd_ = null;
        }
        cmdCase_ = 104;
        onChanged();;
        return getActivityRequestBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.caidt.proto.CsMessage)
    }

    // @@protoc_insertion_point(class_scope:com.caidt.proto.CsMessage)
    private static final com.caidt.proto.ProtoCsMessage.CsMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.caidt.proto.ProtoCsMessage.CsMessage();
    }

    public static com.caidt.proto.ProtoCsMessage.CsMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CsMessage>
        PARSER = new com.google.protobuf.AbstractParser<CsMessage>() {
      public CsMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CsMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CsMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CsMessage> getParserForType() {
      return PARSER;
    }

    public com.caidt.proto.ProtoCsMessage.CsMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_caidt_proto_CsMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_caidt_proto_CsMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026proto_cs_message.proto\022\017com.caidt.prot" +
      "o\032\026proto_descriptor.proto\032\022proto_player." +
      "proto\032\024proto_activity.proto\"\333\001\n\tCsMessag" +
      "e\0225\n\014loginRequest\030e \001(\0132\035.com.caidt.prot" +
      "o.LoginRequestH\000\022G\n\025getAllActivityReques" +
      "t\030g \001(\0132&.com.caidt.proto.GetAllActivity" +
      "RequestH\000\022A\n\022getActivityRequest\030h \001(\0132#." +
      "com.caidt.proto.GetActivityRequestH\000B\005\n\003" +
      "cmdJ\004\010f\020g"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.caidt.proto.ProtoDescriptor.getDescriptor(),
          com.caidt.proto.ProtoPlayer.getDescriptor(),
          com.caidt.proto.ProtoActivity.getDescriptor(),
        }, assigner);
    internal_static_com_caidt_proto_CsMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_caidt_proto_CsMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_caidt_proto_CsMessage_descriptor,
        new java.lang.String[] { "LoginRequest", "GetAllActivityRequest", "GetActivityRequest", "Cmd", });
    com.caidt.proto.ProtoDescriptor.getDescriptor();
    com.caidt.proto.ProtoPlayer.getDescriptor();
    com.caidt.proto.ProtoActivity.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
