// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_cs_message.proto

package com.caidt.proto;

public final class ProtoCsMessage {
  private ProtoCsMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CsMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.caidt.proto.CsMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
     */
    boolean hasLoginRequest();
    /**
     * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
     */
    ProtoBase.LoginRequest getLoginRequest();
    /**
     * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
     */
    ProtoBase.LoginRequestOrBuilder getLoginRequestOrBuilder();

    /**
     * <code>optional .com.caidt.proto.GetPlayerInfoRequest getPlayerInfoRequest = 102;</code>
     */
    boolean hasGetPlayerInfoRequest();
    /**
     * <code>optional .com.caidt.proto.GetPlayerInfoRequest getPlayerInfoRequest = 102;</code>
     */
    ProtoPlayer.GetPlayerInfoRequest getGetPlayerInfoRequest();
    /**
     * <code>optional .com.caidt.proto.GetPlayerInfoRequest getPlayerInfoRequest = 102;</code>
     */
    ProtoPlayer.GetPlayerInfoRequestOrBuilder getGetPlayerInfoRequestOrBuilder();

    public ProtoCsMessage.CsMessage.CmdCase getCmdCase();
  }
  /**
   * Protobuf type {@code com.caidt.proto.CsMessage}
   */
  public  static final class CsMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.caidt.proto.CsMessage)
      CsMessageOrBuilder {
    // Use CsMessage.newBuilder() to construct.
    private CsMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CsMessage() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CsMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 810: {
              ProtoBase.LoginRequest.Builder subBuilder = null;
              if (cmdCase_ == 101) {
                subBuilder = ((ProtoBase.LoginRequest) cmd_).toBuilder();
              }
              cmd_ =
                  input.readMessage(ProtoBase.LoginRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((ProtoBase.LoginRequest) cmd_);
                cmd_ = subBuilder.buildPartial();
              }
              cmdCase_ = 101;
              break;
            }
            case 818: {
              ProtoPlayer.GetPlayerInfoRequest.Builder subBuilder = null;
              if (cmdCase_ == 102) {
                subBuilder = ((ProtoPlayer.GetPlayerInfoRequest) cmd_).toBuilder();
              }
              cmd_ =
                  input.readMessage(ProtoPlayer.GetPlayerInfoRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((ProtoPlayer.GetPlayerInfoRequest) cmd_);
                cmd_ = subBuilder.buildPartial();
              }
              cmdCase_ = 102;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoCsMessage.internal_static_com_caidt_proto_CsMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoCsMessage.internal_static_com_caidt_proto_CsMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoCsMessage.CsMessage.class, ProtoCsMessage.CsMessage.Builder.class);
    }

    private int bitField0_;
    private int cmdCase_ = 0;
    private java.lang.Object cmd_;
    public enum CmdCase
        implements com.google.protobuf.Internal.EnumLite {
      LOGINREQUEST(101),
      GETPLAYERINFOREQUEST(102),
      CMD_NOT_SET(0);
      private final int value;
      private CmdCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static CmdCase valueOf(int value) {
        return forNumber(value);
      }

      public static CmdCase forNumber(int value) {
        switch (value) {
          case 101: return LOGINREQUEST;
          case 102: return GETPLAYERINFOREQUEST;
          case 0: return CMD_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public CmdCase
    getCmdCase() {
      return CmdCase.forNumber(
          cmdCase_);
    }

    public static final int LOGINREQUEST_FIELD_NUMBER = 101;
    /**
     * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
     */
    public boolean hasLoginRequest() {
      return cmdCase_ == 101;
    }
    /**
     * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
     */
    public ProtoBase.LoginRequest getLoginRequest() {
      if (cmdCase_ == 101) {
         return (ProtoBase.LoginRequest) cmd_;
      }
      return ProtoBase.LoginRequest.getDefaultInstance();
    }
    /**
     * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
     */
    public ProtoBase.LoginRequestOrBuilder getLoginRequestOrBuilder() {
      if (cmdCase_ == 101) {
         return (ProtoBase.LoginRequest) cmd_;
      }
      return ProtoBase.LoginRequest.getDefaultInstance();
    }

    public static final int GETPLAYERINFOREQUEST_FIELD_NUMBER = 102;
    /**
     * <code>optional .com.caidt.proto.GetPlayerInfoRequest getPlayerInfoRequest = 102;</code>
     */
    public boolean hasGetPlayerInfoRequest() {
      return cmdCase_ == 102;
    }
    /**
     * <code>optional .com.caidt.proto.GetPlayerInfoRequest getPlayerInfoRequest = 102;</code>
     */
    public ProtoPlayer.GetPlayerInfoRequest getGetPlayerInfoRequest() {
      if (cmdCase_ == 102) {
         return (ProtoPlayer.GetPlayerInfoRequest) cmd_;
      }
      return ProtoPlayer.GetPlayerInfoRequest.getDefaultInstance();
    }
    /**
     * <code>optional .com.caidt.proto.GetPlayerInfoRequest getPlayerInfoRequest = 102;</code>
     */
    public ProtoPlayer.GetPlayerInfoRequestOrBuilder getGetPlayerInfoRequestOrBuilder() {
      if (cmdCase_ == 102) {
         return (ProtoPlayer.GetPlayerInfoRequest) cmd_;
      }
      return ProtoPlayer.GetPlayerInfoRequest.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasLoginRequest()) {
        if (!getLoginRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasGetPlayerInfoRequest()) {
        if (!getGetPlayerInfoRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmdCase_ == 101) {
        output.writeMessage(101, (ProtoBase.LoginRequest) cmd_);
      }
      if (cmdCase_ == 102) {
        output.writeMessage(102, (ProtoPlayer.GetPlayerInfoRequest) cmd_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmdCase_ == 101) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(101, (ProtoBase.LoginRequest) cmd_);
      }
      if (cmdCase_ == 102) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(102, (ProtoPlayer.GetPlayerInfoRequest) cmd_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoCsMessage.CsMessage)) {
        return super.equals(obj);
      }
      ProtoCsMessage.CsMessage other = (ProtoCsMessage.CsMessage) obj;

      boolean result = true;
      result = result && getCmdCase().equals(
          other.getCmdCase());
      if (!result) return false;
      switch (cmdCase_) {
        case 101:
          result = result && getLoginRequest()
              .equals(other.getLoginRequest());
          break;
        case 102:
          result = result && getGetPlayerInfoRequest()
              .equals(other.getGetPlayerInfoRequest());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      switch (cmdCase_) {
        case 101:
          hash = (37 * hash) + LOGINREQUEST_FIELD_NUMBER;
          hash = (53 * hash) + getLoginRequest().hashCode();
          break;
        case 102:
          hash = (37 * hash) + GETPLAYERINFOREQUEST_FIELD_NUMBER;
          hash = (53 * hash) + getGetPlayerInfoRequest().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoCsMessage.CsMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoCsMessage.CsMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoCsMessage.CsMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoCsMessage.CsMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoCsMessage.CsMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoCsMessage.CsMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoCsMessage.CsMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtoCsMessage.CsMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoCsMessage.CsMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoCsMessage.CsMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoCsMessage.CsMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.caidt.proto.CsMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.caidt.proto.CsMessage)
        ProtoCsMessage.CsMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoCsMessage.internal_static_com_caidt_proto_CsMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoCsMessage.internal_static_com_caidt_proto_CsMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoCsMessage.CsMessage.class, ProtoCsMessage.CsMessage.Builder.class);
      }

      // Construct using com.caidt.proto.ProtoCsMessage.CsMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        cmdCase_ = 0;
        cmd_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoCsMessage.internal_static_com_caidt_proto_CsMessage_descriptor;
      }

      public ProtoCsMessage.CsMessage getDefaultInstanceForType() {
        return ProtoCsMessage.CsMessage.getDefaultInstance();
      }

      public ProtoCsMessage.CsMessage build() {
        ProtoCsMessage.CsMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoCsMessage.CsMessage buildPartial() {
        ProtoCsMessage.CsMessage result = new ProtoCsMessage.CsMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (cmdCase_ == 101) {
          if (loginRequestBuilder_ == null) {
            result.cmd_ = cmd_;
          } else {
            result.cmd_ = loginRequestBuilder_.build();
          }
        }
        if (cmdCase_ == 102) {
          if (getPlayerInfoRequestBuilder_ == null) {
            result.cmd_ = cmd_;
          } else {
            result.cmd_ = getPlayerInfoRequestBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.cmdCase_ = cmdCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoCsMessage.CsMessage) {
          return mergeFrom((ProtoCsMessage.CsMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoCsMessage.CsMessage other) {
        if (other == ProtoCsMessage.CsMessage.getDefaultInstance()) return this;
        switch (other.getCmdCase()) {
          case LOGINREQUEST: {
            mergeLoginRequest(other.getLoginRequest());
            break;
          }
          case GETPLAYERINFOREQUEST: {
            mergeGetPlayerInfoRequest(other.getGetPlayerInfoRequest());
            break;
          }
          case CMD_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (hasLoginRequest()) {
          if (!getLoginRequest().isInitialized()) {
            return false;
          }
        }
        if (hasGetPlayerInfoRequest()) {
          if (!getGetPlayerInfoRequest().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoCsMessage.CsMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoCsMessage.CsMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int cmdCase_ = 0;
      private java.lang.Object cmd_;
      public CmdCase
          getCmdCase() {
        return CmdCase.forNumber(
            cmdCase_);
      }

      public Builder clearCmd() {
        cmdCase_ = 0;
        cmd_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilderV3<
          ProtoBase.LoginRequest, ProtoBase.LoginRequest.Builder, ProtoBase.LoginRequestOrBuilder> loginRequestBuilder_;
      /**
       * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
       */
      public boolean hasLoginRequest() {
        return cmdCase_ == 101;
      }
      /**
       * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
       */
      public ProtoBase.LoginRequest getLoginRequest() {
        if (loginRequestBuilder_ == null) {
          if (cmdCase_ == 101) {
            return (ProtoBase.LoginRequest) cmd_;
          }
          return ProtoBase.LoginRequest.getDefaultInstance();
        } else {
          if (cmdCase_ == 101) {
            return loginRequestBuilder_.getMessage();
          }
          return ProtoBase.LoginRequest.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
       */
      public Builder setLoginRequest(ProtoBase.LoginRequest value) {
        if (loginRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cmd_ = value;
          onChanged();
        } else {
          loginRequestBuilder_.setMessage(value);
        }
        cmdCase_ = 101;
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
       */
      public Builder setLoginRequest(
          ProtoBase.LoginRequest.Builder builderForValue) {
        if (loginRequestBuilder_ == null) {
          cmd_ = builderForValue.build();
          onChanged();
        } else {
          loginRequestBuilder_.setMessage(builderForValue.build());
        }
        cmdCase_ = 101;
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
       */
      public Builder mergeLoginRequest(ProtoBase.LoginRequest value) {
        if (loginRequestBuilder_ == null) {
          if (cmdCase_ == 101 &&
              cmd_ != ProtoBase.LoginRequest.getDefaultInstance()) {
            cmd_ = ProtoBase.LoginRequest.newBuilder((ProtoBase.LoginRequest) cmd_)
                .mergeFrom(value).buildPartial();
          } else {
            cmd_ = value;
          }
          onChanged();
        } else {
          if (cmdCase_ == 101) {
            loginRequestBuilder_.mergeFrom(value);
          }
          loginRequestBuilder_.setMessage(value);
        }
        cmdCase_ = 101;
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
       */
      public Builder clearLoginRequest() {
        if (loginRequestBuilder_ == null) {
          if (cmdCase_ == 101) {
            cmdCase_ = 0;
            cmd_ = null;
            onChanged();
          }
        } else {
          if (cmdCase_ == 101) {
            cmdCase_ = 0;
            cmd_ = null;
          }
          loginRequestBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
       */
      public ProtoBase.LoginRequest.Builder getLoginRequestBuilder() {
        return getLoginRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
       */
      public ProtoBase.LoginRequestOrBuilder getLoginRequestOrBuilder() {
        if ((cmdCase_ == 101) && (loginRequestBuilder_ != null)) {
          return loginRequestBuilder_.getMessageOrBuilder();
        } else {
          if (cmdCase_ == 101) {
            return (ProtoBase.LoginRequest) cmd_;
          }
          return ProtoBase.LoginRequest.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.caidt.proto.LoginRequest loginRequest = 101;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ProtoBase.LoginRequest, ProtoBase.LoginRequest.Builder, ProtoBase.LoginRequestOrBuilder>
          getLoginRequestFieldBuilder() {
        if (loginRequestBuilder_ == null) {
          if (!(cmdCase_ == 101)) {
            cmd_ = ProtoBase.LoginRequest.getDefaultInstance();
          }
          loginRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ProtoBase.LoginRequest, ProtoBase.LoginRequest.Builder, ProtoBase.LoginRequestOrBuilder>(
                  (ProtoBase.LoginRequest) cmd_,
                  getParentForChildren(),
                  isClean());
          cmd_ = null;
        }
        cmdCase_ = 101;
        onChanged();;
        return loginRequestBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          ProtoPlayer.GetPlayerInfoRequest, ProtoPlayer.GetPlayerInfoRequest.Builder, ProtoPlayer.GetPlayerInfoRequestOrBuilder> getPlayerInfoRequestBuilder_;
      /**
       * <code>optional .com.caidt.proto.GetPlayerInfoRequest getPlayerInfoRequest = 102;</code>
       */
      public boolean hasGetPlayerInfoRequest() {
        return cmdCase_ == 102;
      }
      /**
       * <code>optional .com.caidt.proto.GetPlayerInfoRequest getPlayerInfoRequest = 102;</code>
       */
      public ProtoPlayer.GetPlayerInfoRequest getGetPlayerInfoRequest() {
        if (getPlayerInfoRequestBuilder_ == null) {
          if (cmdCase_ == 102) {
            return (ProtoPlayer.GetPlayerInfoRequest) cmd_;
          }
          return ProtoPlayer.GetPlayerInfoRequest.getDefaultInstance();
        } else {
          if (cmdCase_ == 102) {
            return getPlayerInfoRequestBuilder_.getMessage();
          }
          return ProtoPlayer.GetPlayerInfoRequest.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.caidt.proto.GetPlayerInfoRequest getPlayerInfoRequest = 102;</code>
       */
      public Builder setGetPlayerInfoRequest(ProtoPlayer.GetPlayerInfoRequest value) {
        if (getPlayerInfoRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cmd_ = value;
          onChanged();
        } else {
          getPlayerInfoRequestBuilder_.setMessage(value);
        }
        cmdCase_ = 102;
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.GetPlayerInfoRequest getPlayerInfoRequest = 102;</code>
       */
      public Builder setGetPlayerInfoRequest(
          ProtoPlayer.GetPlayerInfoRequest.Builder builderForValue) {
        if (getPlayerInfoRequestBuilder_ == null) {
          cmd_ = builderForValue.build();
          onChanged();
        } else {
          getPlayerInfoRequestBuilder_.setMessage(builderForValue.build());
        }
        cmdCase_ = 102;
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.GetPlayerInfoRequest getPlayerInfoRequest = 102;</code>
       */
      public Builder mergeGetPlayerInfoRequest(ProtoPlayer.GetPlayerInfoRequest value) {
        if (getPlayerInfoRequestBuilder_ == null) {
          if (cmdCase_ == 102 &&
              cmd_ != ProtoPlayer.GetPlayerInfoRequest.getDefaultInstance()) {
            cmd_ = ProtoPlayer.GetPlayerInfoRequest.newBuilder((ProtoPlayer.GetPlayerInfoRequest) cmd_)
                .mergeFrom(value).buildPartial();
          } else {
            cmd_ = value;
          }
          onChanged();
        } else {
          if (cmdCase_ == 102) {
            getPlayerInfoRequestBuilder_.mergeFrom(value);
          }
          getPlayerInfoRequestBuilder_.setMessage(value);
        }
        cmdCase_ = 102;
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.GetPlayerInfoRequest getPlayerInfoRequest = 102;</code>
       */
      public Builder clearGetPlayerInfoRequest() {
        if (getPlayerInfoRequestBuilder_ == null) {
          if (cmdCase_ == 102) {
            cmdCase_ = 0;
            cmd_ = null;
            onChanged();
          }
        } else {
          if (cmdCase_ == 102) {
            cmdCase_ = 0;
            cmd_ = null;
          }
          getPlayerInfoRequestBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.GetPlayerInfoRequest getPlayerInfoRequest = 102;</code>
       */
      public ProtoPlayer.GetPlayerInfoRequest.Builder getGetPlayerInfoRequestBuilder() {
        return getGetPlayerInfoRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.caidt.proto.GetPlayerInfoRequest getPlayerInfoRequest = 102;</code>
       */
      public ProtoPlayer.GetPlayerInfoRequestOrBuilder getGetPlayerInfoRequestOrBuilder() {
        if ((cmdCase_ == 102) && (getPlayerInfoRequestBuilder_ != null)) {
          return getPlayerInfoRequestBuilder_.getMessageOrBuilder();
        } else {
          if (cmdCase_ == 102) {
            return (ProtoPlayer.GetPlayerInfoRequest) cmd_;
          }
          return ProtoPlayer.GetPlayerInfoRequest.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.caidt.proto.GetPlayerInfoRequest getPlayerInfoRequest = 102;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ProtoPlayer.GetPlayerInfoRequest, ProtoPlayer.GetPlayerInfoRequest.Builder, ProtoPlayer.GetPlayerInfoRequestOrBuilder>
          getGetPlayerInfoRequestFieldBuilder() {
        if (getPlayerInfoRequestBuilder_ == null) {
          if (!(cmdCase_ == 102)) {
            cmd_ = ProtoPlayer.GetPlayerInfoRequest.getDefaultInstance();
          }
          getPlayerInfoRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ProtoPlayer.GetPlayerInfoRequest, ProtoPlayer.GetPlayerInfoRequest.Builder, ProtoPlayer.GetPlayerInfoRequestOrBuilder>(
                  (ProtoPlayer.GetPlayerInfoRequest) cmd_,
                  getParentForChildren(),
                  isClean());
          cmd_ = null;
        }
        cmdCase_ = 102;
        onChanged();;
        return getPlayerInfoRequestBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.caidt.proto.CsMessage)
    }

    // @@protoc_insertion_point(class_scope:com.caidt.proto.CsMessage)
    private static final ProtoCsMessage.CsMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoCsMessage.CsMessage();
    }

    public static ProtoCsMessage.CsMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CsMessage>
        PARSER = new com.google.protobuf.AbstractParser<CsMessage>() {
      public CsMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CsMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CsMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CsMessage> getParserForType() {
      return PARSER;
    }

    public ProtoCsMessage.CsMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_caidt_proto_CsMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_caidt_proto_CsMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026proto_cs_message.proto\022\017com.caidt.prot" +
      "o\032\020proto_base.proto\032\022proto_player.proto\"" +
      "\220\001\n\tCsMessage\0225\n\014loginRequest\030e \001(\0132\035.co" +
      "m.caidt.proto.LoginRequestH\000\022E\n\024getPlaye" +
      "rInfoRequest\030f \001(\0132%.com.caidt.proto.Get" +
      "PlayerInfoRequestH\000B\005\n\003cmd"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ProtoBase.getDescriptor(),
          ProtoPlayer.getDescriptor(),
        }, assigner);
    internal_static_com_caidt_proto_CsMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_caidt_proto_CsMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_caidt_proto_CsMessage_descriptor,
        new java.lang.String[] { "LoginRequest", "GetPlayerInfoRequest", "Cmd", });
    ProtoBase.getDescriptor();
    ProtoPlayer.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
