// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_sc_message.proto

package com.caidt.proto;

public final class ProtoScMessage {
  private ProtoScMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ScMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.caidt.proto.ScMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
     */
    boolean hasLoginResponse();
    /**
     * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
     */
    ProtoBase.LoginResponse getLoginResponse();
    /**
     * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
     */
    ProtoBase.LoginResponseOrBuilder getLoginResponseOrBuilder();

    /**
     * <code>optional .com.caidt.proto.GetPlayerInfoResponse getPlayerInfoResponse = 102;</code>
     */
    boolean hasGetPlayerInfoResponse();
    /**
     * <code>optional .com.caidt.proto.GetPlayerInfoResponse getPlayerInfoResponse = 102;</code>
     */
    ProtoPlayer.GetPlayerInfoResponse getGetPlayerInfoResponse();
    /**
     * <code>optional .com.caidt.proto.GetPlayerInfoResponse getPlayerInfoResponse = 102;</code>
     */
    ProtoPlayer.GetPlayerInfoResponseOrBuilder getGetPlayerInfoResponseOrBuilder();

    public ProtoScMessage.ScMessage.CmdCase getCmdCase();
  }
  /**
   * Protobuf type {@code com.caidt.proto.ScMessage}
   */
  public  static final class ScMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.caidt.proto.ScMessage)
      ScMessageOrBuilder {
    // Use ScMessage.newBuilder() to construct.
    private ScMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ScMessage() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ScMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 810: {
              ProtoBase.LoginResponse.Builder subBuilder = null;
              if (cmdCase_ == 101) {
                subBuilder = ((ProtoBase.LoginResponse) cmd_).toBuilder();
              }
              cmd_ =
                  input.readMessage(ProtoBase.LoginResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((ProtoBase.LoginResponse) cmd_);
                cmd_ = subBuilder.buildPartial();
              }
              cmdCase_ = 101;
              break;
            }
            case 818: {
              ProtoPlayer.GetPlayerInfoResponse.Builder subBuilder = null;
              if (cmdCase_ == 102) {
                subBuilder = ((ProtoPlayer.GetPlayerInfoResponse) cmd_).toBuilder();
              }
              cmd_ =
                  input.readMessage(ProtoPlayer.GetPlayerInfoResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((ProtoPlayer.GetPlayerInfoResponse) cmd_);
                cmd_ = subBuilder.buildPartial();
              }
              cmdCase_ = 102;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoScMessage.internal_static_com_caidt_proto_ScMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoScMessage.internal_static_com_caidt_proto_ScMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoScMessage.ScMessage.class, ProtoScMessage.ScMessage.Builder.class);
    }

    private int bitField0_;
    private int cmdCase_ = 0;
    private java.lang.Object cmd_;
    public enum CmdCase
        implements com.google.protobuf.Internal.EnumLite {
      LOGINRESPONSE(101),
      GETPLAYERINFORESPONSE(102),
      CMD_NOT_SET(0);
      private final int value;
      private CmdCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static CmdCase valueOf(int value) {
        return forNumber(value);
      }

      public static CmdCase forNumber(int value) {
        switch (value) {
          case 101: return LOGINRESPONSE;
          case 102: return GETPLAYERINFORESPONSE;
          case 0: return CMD_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public CmdCase
    getCmdCase() {
      return CmdCase.forNumber(
          cmdCase_);
    }

    public static final int LOGINRESPONSE_FIELD_NUMBER = 101;
    /**
     * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
     */
    public boolean hasLoginResponse() {
      return cmdCase_ == 101;
    }
    /**
     * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
     */
    public ProtoBase.LoginResponse getLoginResponse() {
      if (cmdCase_ == 101) {
         return (ProtoBase.LoginResponse) cmd_;
      }
      return ProtoBase.LoginResponse.getDefaultInstance();
    }
    /**
     * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
     */
    public ProtoBase.LoginResponseOrBuilder getLoginResponseOrBuilder() {
      if (cmdCase_ == 101) {
         return (ProtoBase.LoginResponse) cmd_;
      }
      return ProtoBase.LoginResponse.getDefaultInstance();
    }

    public static final int GETPLAYERINFORESPONSE_FIELD_NUMBER = 102;
    /**
     * <code>optional .com.caidt.proto.GetPlayerInfoResponse getPlayerInfoResponse = 102;</code>
     */
    public boolean hasGetPlayerInfoResponse() {
      return cmdCase_ == 102;
    }
    /**
     * <code>optional .com.caidt.proto.GetPlayerInfoResponse getPlayerInfoResponse = 102;</code>
     */
    public ProtoPlayer.GetPlayerInfoResponse getGetPlayerInfoResponse() {
      if (cmdCase_ == 102) {
         return (ProtoPlayer.GetPlayerInfoResponse) cmd_;
      }
      return ProtoPlayer.GetPlayerInfoResponse.getDefaultInstance();
    }
    /**
     * <code>optional .com.caidt.proto.GetPlayerInfoResponse getPlayerInfoResponse = 102;</code>
     */
    public ProtoPlayer.GetPlayerInfoResponseOrBuilder getGetPlayerInfoResponseOrBuilder() {
      if (cmdCase_ == 102) {
         return (ProtoPlayer.GetPlayerInfoResponse) cmd_;
      }
      return ProtoPlayer.GetPlayerInfoResponse.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasLoginResponse()) {
        if (!getLoginResponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasGetPlayerInfoResponse()) {
        if (!getGetPlayerInfoResponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmdCase_ == 101) {
        output.writeMessage(101, (ProtoBase.LoginResponse) cmd_);
      }
      if (cmdCase_ == 102) {
        output.writeMessage(102, (ProtoPlayer.GetPlayerInfoResponse) cmd_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmdCase_ == 101) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(101, (ProtoBase.LoginResponse) cmd_);
      }
      if (cmdCase_ == 102) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(102, (ProtoPlayer.GetPlayerInfoResponse) cmd_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoScMessage.ScMessage)) {
        return super.equals(obj);
      }
      ProtoScMessage.ScMessage other = (ProtoScMessage.ScMessage) obj;

      boolean result = true;
      result = result && getCmdCase().equals(
          other.getCmdCase());
      if (!result) return false;
      switch (cmdCase_) {
        case 101:
          result = result && getLoginResponse()
              .equals(other.getLoginResponse());
          break;
        case 102:
          result = result && getGetPlayerInfoResponse()
              .equals(other.getGetPlayerInfoResponse());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      switch (cmdCase_) {
        case 101:
          hash = (37 * hash) + LOGINRESPONSE_FIELD_NUMBER;
          hash = (53 * hash) + getLoginResponse().hashCode();
          break;
        case 102:
          hash = (37 * hash) + GETPLAYERINFORESPONSE_FIELD_NUMBER;
          hash = (53 * hash) + getGetPlayerInfoResponse().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoScMessage.ScMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoScMessage.ScMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoScMessage.ScMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoScMessage.ScMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoScMessage.ScMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoScMessage.ScMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoScMessage.ScMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtoScMessage.ScMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoScMessage.ScMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoScMessage.ScMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoScMessage.ScMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.caidt.proto.ScMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.caidt.proto.ScMessage)
        ProtoScMessage.ScMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoScMessage.internal_static_com_caidt_proto_ScMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoScMessage.internal_static_com_caidt_proto_ScMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoScMessage.ScMessage.class, ProtoScMessage.ScMessage.Builder.class);
      }

      // Construct using com.caidt.proto.ProtoScMessage.ScMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        cmdCase_ = 0;
        cmd_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoScMessage.internal_static_com_caidt_proto_ScMessage_descriptor;
      }

      public ProtoScMessage.ScMessage getDefaultInstanceForType() {
        return ProtoScMessage.ScMessage.getDefaultInstance();
      }

      public ProtoScMessage.ScMessage build() {
        ProtoScMessage.ScMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoScMessage.ScMessage buildPartial() {
        ProtoScMessage.ScMessage result = new ProtoScMessage.ScMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (cmdCase_ == 101) {
          if (loginResponseBuilder_ == null) {
            result.cmd_ = cmd_;
          } else {
            result.cmd_ = loginResponseBuilder_.build();
          }
        }
        if (cmdCase_ == 102) {
          if (getPlayerInfoResponseBuilder_ == null) {
            result.cmd_ = cmd_;
          } else {
            result.cmd_ = getPlayerInfoResponseBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.cmdCase_ = cmdCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoScMessage.ScMessage) {
          return mergeFrom((ProtoScMessage.ScMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoScMessage.ScMessage other) {
        if (other == ProtoScMessage.ScMessage.getDefaultInstance()) return this;
        switch (other.getCmdCase()) {
          case LOGINRESPONSE: {
            mergeLoginResponse(other.getLoginResponse());
            break;
          }
          case GETPLAYERINFORESPONSE: {
            mergeGetPlayerInfoResponse(other.getGetPlayerInfoResponse());
            break;
          }
          case CMD_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (hasLoginResponse()) {
          if (!getLoginResponse().isInitialized()) {
            return false;
          }
        }
        if (hasGetPlayerInfoResponse()) {
          if (!getGetPlayerInfoResponse().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoScMessage.ScMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoScMessage.ScMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int cmdCase_ = 0;
      private java.lang.Object cmd_;
      public CmdCase
          getCmdCase() {
        return CmdCase.forNumber(
            cmdCase_);
      }

      public Builder clearCmd() {
        cmdCase_ = 0;
        cmd_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilderV3<
          ProtoBase.LoginResponse, ProtoBase.LoginResponse.Builder, ProtoBase.LoginResponseOrBuilder> loginResponseBuilder_;
      /**
       * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
       */
      public boolean hasLoginResponse() {
        return cmdCase_ == 101;
      }
      /**
       * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
       */
      public ProtoBase.LoginResponse getLoginResponse() {
        if (loginResponseBuilder_ == null) {
          if (cmdCase_ == 101) {
            return (ProtoBase.LoginResponse) cmd_;
          }
          return ProtoBase.LoginResponse.getDefaultInstance();
        } else {
          if (cmdCase_ == 101) {
            return loginResponseBuilder_.getMessage();
          }
          return ProtoBase.LoginResponse.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
       */
      public Builder setLoginResponse(ProtoBase.LoginResponse value) {
        if (loginResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cmd_ = value;
          onChanged();
        } else {
          loginResponseBuilder_.setMessage(value);
        }
        cmdCase_ = 101;
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
       */
      public Builder setLoginResponse(
          ProtoBase.LoginResponse.Builder builderForValue) {
        if (loginResponseBuilder_ == null) {
          cmd_ = builderForValue.build();
          onChanged();
        } else {
          loginResponseBuilder_.setMessage(builderForValue.build());
        }
        cmdCase_ = 101;
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
       */
      public Builder mergeLoginResponse(ProtoBase.LoginResponse value) {
        if (loginResponseBuilder_ == null) {
          if (cmdCase_ == 101 &&
              cmd_ != ProtoBase.LoginResponse.getDefaultInstance()) {
            cmd_ = ProtoBase.LoginResponse.newBuilder((ProtoBase.LoginResponse) cmd_)
                .mergeFrom(value).buildPartial();
          } else {
            cmd_ = value;
          }
          onChanged();
        } else {
          if (cmdCase_ == 101) {
            loginResponseBuilder_.mergeFrom(value);
          }
          loginResponseBuilder_.setMessage(value);
        }
        cmdCase_ = 101;
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
       */
      public Builder clearLoginResponse() {
        if (loginResponseBuilder_ == null) {
          if (cmdCase_ == 101) {
            cmdCase_ = 0;
            cmd_ = null;
            onChanged();
          }
        } else {
          if (cmdCase_ == 101) {
            cmdCase_ = 0;
            cmd_ = null;
          }
          loginResponseBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
       */
      public ProtoBase.LoginResponse.Builder getLoginResponseBuilder() {
        return getLoginResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
       */
      public ProtoBase.LoginResponseOrBuilder getLoginResponseOrBuilder() {
        if ((cmdCase_ == 101) && (loginResponseBuilder_ != null)) {
          return loginResponseBuilder_.getMessageOrBuilder();
        } else {
          if (cmdCase_ == 101) {
            return (ProtoBase.LoginResponse) cmd_;
          }
          return ProtoBase.LoginResponse.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ProtoBase.LoginResponse, ProtoBase.LoginResponse.Builder, ProtoBase.LoginResponseOrBuilder>
          getLoginResponseFieldBuilder() {
        if (loginResponseBuilder_ == null) {
          if (!(cmdCase_ == 101)) {
            cmd_ = ProtoBase.LoginResponse.getDefaultInstance();
          }
          loginResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ProtoBase.LoginResponse, ProtoBase.LoginResponse.Builder, ProtoBase.LoginResponseOrBuilder>(
                  (ProtoBase.LoginResponse) cmd_,
                  getParentForChildren(),
                  isClean());
          cmd_ = null;
        }
        cmdCase_ = 101;
        onChanged();;
        return loginResponseBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          ProtoPlayer.GetPlayerInfoResponse, ProtoPlayer.GetPlayerInfoResponse.Builder, ProtoPlayer.GetPlayerInfoResponseOrBuilder> getPlayerInfoResponseBuilder_;
      /**
       * <code>optional .com.caidt.proto.GetPlayerInfoResponse getPlayerInfoResponse = 102;</code>
       */
      public boolean hasGetPlayerInfoResponse() {
        return cmdCase_ == 102;
      }
      /**
       * <code>optional .com.caidt.proto.GetPlayerInfoResponse getPlayerInfoResponse = 102;</code>
       */
      public ProtoPlayer.GetPlayerInfoResponse getGetPlayerInfoResponse() {
        if (getPlayerInfoResponseBuilder_ == null) {
          if (cmdCase_ == 102) {
            return (ProtoPlayer.GetPlayerInfoResponse) cmd_;
          }
          return ProtoPlayer.GetPlayerInfoResponse.getDefaultInstance();
        } else {
          if (cmdCase_ == 102) {
            return getPlayerInfoResponseBuilder_.getMessage();
          }
          return ProtoPlayer.GetPlayerInfoResponse.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.caidt.proto.GetPlayerInfoResponse getPlayerInfoResponse = 102;</code>
       */
      public Builder setGetPlayerInfoResponse(ProtoPlayer.GetPlayerInfoResponse value) {
        if (getPlayerInfoResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cmd_ = value;
          onChanged();
        } else {
          getPlayerInfoResponseBuilder_.setMessage(value);
        }
        cmdCase_ = 102;
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.GetPlayerInfoResponse getPlayerInfoResponse = 102;</code>
       */
      public Builder setGetPlayerInfoResponse(
          ProtoPlayer.GetPlayerInfoResponse.Builder builderForValue) {
        if (getPlayerInfoResponseBuilder_ == null) {
          cmd_ = builderForValue.build();
          onChanged();
        } else {
          getPlayerInfoResponseBuilder_.setMessage(builderForValue.build());
        }
        cmdCase_ = 102;
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.GetPlayerInfoResponse getPlayerInfoResponse = 102;</code>
       */
      public Builder mergeGetPlayerInfoResponse(ProtoPlayer.GetPlayerInfoResponse value) {
        if (getPlayerInfoResponseBuilder_ == null) {
          if (cmdCase_ == 102 &&
              cmd_ != ProtoPlayer.GetPlayerInfoResponse.getDefaultInstance()) {
            cmd_ = ProtoPlayer.GetPlayerInfoResponse.newBuilder((ProtoPlayer.GetPlayerInfoResponse) cmd_)
                .mergeFrom(value).buildPartial();
          } else {
            cmd_ = value;
          }
          onChanged();
        } else {
          if (cmdCase_ == 102) {
            getPlayerInfoResponseBuilder_.mergeFrom(value);
          }
          getPlayerInfoResponseBuilder_.setMessage(value);
        }
        cmdCase_ = 102;
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.GetPlayerInfoResponse getPlayerInfoResponse = 102;</code>
       */
      public Builder clearGetPlayerInfoResponse() {
        if (getPlayerInfoResponseBuilder_ == null) {
          if (cmdCase_ == 102) {
            cmdCase_ = 0;
            cmd_ = null;
            onChanged();
          }
        } else {
          if (cmdCase_ == 102) {
            cmdCase_ = 0;
            cmd_ = null;
          }
          getPlayerInfoResponseBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.GetPlayerInfoResponse getPlayerInfoResponse = 102;</code>
       */
      public ProtoPlayer.GetPlayerInfoResponse.Builder getGetPlayerInfoResponseBuilder() {
        return getGetPlayerInfoResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.caidt.proto.GetPlayerInfoResponse getPlayerInfoResponse = 102;</code>
       */
      public ProtoPlayer.GetPlayerInfoResponseOrBuilder getGetPlayerInfoResponseOrBuilder() {
        if ((cmdCase_ == 102) && (getPlayerInfoResponseBuilder_ != null)) {
          return getPlayerInfoResponseBuilder_.getMessageOrBuilder();
        } else {
          if (cmdCase_ == 102) {
            return (ProtoPlayer.GetPlayerInfoResponse) cmd_;
          }
          return ProtoPlayer.GetPlayerInfoResponse.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.caidt.proto.GetPlayerInfoResponse getPlayerInfoResponse = 102;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ProtoPlayer.GetPlayerInfoResponse, ProtoPlayer.GetPlayerInfoResponse.Builder, ProtoPlayer.GetPlayerInfoResponseOrBuilder>
          getGetPlayerInfoResponseFieldBuilder() {
        if (getPlayerInfoResponseBuilder_ == null) {
          if (!(cmdCase_ == 102)) {
            cmd_ = ProtoPlayer.GetPlayerInfoResponse.getDefaultInstance();
          }
          getPlayerInfoResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ProtoPlayer.GetPlayerInfoResponse, ProtoPlayer.GetPlayerInfoResponse.Builder, ProtoPlayer.GetPlayerInfoResponseOrBuilder>(
                  (ProtoPlayer.GetPlayerInfoResponse) cmd_,
                  getParentForChildren(),
                  isClean());
          cmd_ = null;
        }
        cmdCase_ = 102;
        onChanged();;
        return getPlayerInfoResponseBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.caidt.proto.ScMessage)
    }

    // @@protoc_insertion_point(class_scope:com.caidt.proto.ScMessage)
    private static final ProtoScMessage.ScMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoScMessage.ScMessage();
    }

    public static ProtoScMessage.ScMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ScMessage>
        PARSER = new com.google.protobuf.AbstractParser<ScMessage>() {
      public ScMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ScMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ScMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ScMessage> getParserForType() {
      return PARSER;
    }

    public ProtoScMessage.ScMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_caidt_proto_ScMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_caidt_proto_ScMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026proto_sc_message.proto\022\017com.caidt.prot" +
      "o\032\020proto_base.proto\032\022proto_player.proto\"" +
      "\224\001\n\tScMessage\0227\n\rloginResponse\030e \001(\0132\036.c" +
      "om.caidt.proto.LoginResponseH\000\022G\n\025getPla" +
      "yerInfoResponse\030f \001(\0132&.com.caidt.proto." +
      "GetPlayerInfoResponseH\000B\005\n\003cmd"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ProtoBase.getDescriptor(),
          ProtoPlayer.getDescriptor(),
        }, assigner);
    internal_static_com_caidt_proto_ScMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_caidt_proto_ScMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_caidt_proto_ScMessage_descriptor,
        new java.lang.String[] { "LoginResponse", "GetPlayerInfoResponse", "Cmd", });
    ProtoBase.getDescriptor();
    ProtoPlayer.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
