// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_sc_message.proto

package com.caidt.proto;

public final class ProtoScMessage {
  private ProtoScMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ScMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.caidt.proto.ScMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *        Pong pong = 1;
     * </pre>
     *
     * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
     */
    boolean hasLoginResponse();
    /**
     * <pre>
     *        Pong pong = 1;
     * </pre>
     *
     * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
     */
    com.caidt.proto.ProtoDescriptor.LoginResponse getLoginResponse();
    /**
     * <pre>
     *        Pong pong = 1;
     * </pre>
     *
     * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
     */
    com.caidt.proto.ProtoDescriptor.LoginResponseOrBuilder getLoginResponseOrBuilder();

    /**
     * <pre>
     *        GetPlayerInfoResponse getPlayerInfoResponse = 102;
     * </pre>
     *
     * <code>optional .com.caidt.proto.GetAllActivityResponse GetAllActivityResponse = 103;</code>
     */
    boolean hasGetAllActivityResponse();
    /**
     * <pre>
     *        GetPlayerInfoResponse getPlayerInfoResponse = 102;
     * </pre>
     *
     * <code>optional .com.caidt.proto.GetAllActivityResponse GetAllActivityResponse = 103;</code>
     */
    com.caidt.proto.ProtoActivity.GetAllActivityResponse getGetAllActivityResponse();
    /**
     * <pre>
     *        GetPlayerInfoResponse getPlayerInfoResponse = 102;
     * </pre>
     *
     * <code>optional .com.caidt.proto.GetAllActivityResponse GetAllActivityResponse = 103;</code>
     */
    com.caidt.proto.ProtoActivity.GetAllActivityResponseOrBuilder getGetAllActivityResponseOrBuilder();

    /**
     * <code>optional .com.caidt.proto.GetActivityResponse getActivityResponse = 104;</code>
     */
    boolean hasGetActivityResponse();
    /**
     * <code>optional .com.caidt.proto.GetActivityResponse getActivityResponse = 104;</code>
     */
    com.caidt.proto.ProtoActivity.GetActivityResponse getGetActivityResponse();
    /**
     * <code>optional .com.caidt.proto.GetActivityResponse getActivityResponse = 104;</code>
     */
    com.caidt.proto.ProtoActivity.GetActivityResponseOrBuilder getGetActivityResponseOrBuilder();

    /**
     * <code>optional .com.caidt.proto.ScActivity scActivity = 105;</code>
     */
    boolean hasScActivity();
    /**
     * <code>optional .com.caidt.proto.ScActivity scActivity = 105;</code>
     */
    com.caidt.proto.ProtoActivity.ScActivity getScActivity();
    /**
     * <code>optional .com.caidt.proto.ScActivity scActivity = 105;</code>
     */
    com.caidt.proto.ProtoActivity.ScActivityOrBuilder getScActivityOrBuilder();

    public com.caidt.proto.ProtoScMessage.ScMessage.CmdCase getCmdCase();
  }
  /**
   * Protobuf type {@code com.caidt.proto.ScMessage}
   */
  public  static final class ScMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.caidt.proto.ScMessage)
      ScMessageOrBuilder {
    // Use ScMessage.newBuilder() to construct.
    private ScMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ScMessage() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ScMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 810: {
              com.caidt.proto.ProtoDescriptor.LoginResponse.Builder subBuilder = null;
              if (cmdCase_ == 101) {
                subBuilder = ((com.caidt.proto.ProtoDescriptor.LoginResponse) cmd_).toBuilder();
              }
              cmd_ =
                  input.readMessage(com.caidt.proto.ProtoDescriptor.LoginResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.caidt.proto.ProtoDescriptor.LoginResponse) cmd_);
                cmd_ = subBuilder.buildPartial();
              }
              cmdCase_ = 101;
              break;
            }
            case 826: {
              com.caidt.proto.ProtoActivity.GetAllActivityResponse.Builder subBuilder = null;
              if (cmdCase_ == 103) {
                subBuilder = ((com.caidt.proto.ProtoActivity.GetAllActivityResponse) cmd_).toBuilder();
              }
              cmd_ =
                  input.readMessage(com.caidt.proto.ProtoActivity.GetAllActivityResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.caidt.proto.ProtoActivity.GetAllActivityResponse) cmd_);
                cmd_ = subBuilder.buildPartial();
              }
              cmdCase_ = 103;
              break;
            }
            case 834: {
              com.caidt.proto.ProtoActivity.GetActivityResponse.Builder subBuilder = null;
              if (cmdCase_ == 104) {
                subBuilder = ((com.caidt.proto.ProtoActivity.GetActivityResponse) cmd_).toBuilder();
              }
              cmd_ =
                  input.readMessage(com.caidt.proto.ProtoActivity.GetActivityResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.caidt.proto.ProtoActivity.GetActivityResponse) cmd_);
                cmd_ = subBuilder.buildPartial();
              }
              cmdCase_ = 104;
              break;
            }
            case 842: {
              com.caidt.proto.ProtoActivity.ScActivity.Builder subBuilder = null;
              if (cmdCase_ == 105) {
                subBuilder = ((com.caidt.proto.ProtoActivity.ScActivity) cmd_).toBuilder();
              }
              cmd_ =
                  input.readMessage(com.caidt.proto.ProtoActivity.ScActivity.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.caidt.proto.ProtoActivity.ScActivity) cmd_);
                cmd_ = subBuilder.buildPartial();
              }
              cmdCase_ = 105;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.caidt.proto.ProtoScMessage.internal_static_com_caidt_proto_ScMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.caidt.proto.ProtoScMessage.internal_static_com_caidt_proto_ScMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.caidt.proto.ProtoScMessage.ScMessage.class, com.caidt.proto.ProtoScMessage.ScMessage.Builder.class);
    }

    private int bitField0_;
    private int cmdCase_ = 0;
    private java.lang.Object cmd_;
    public enum CmdCase
        implements com.google.protobuf.Internal.EnumLite {
      LOGINRESPONSE(101),
      GETALLACTIVITYRESPONSE(103),
      GETACTIVITYRESPONSE(104),
      SCACTIVITY(105),
      CMD_NOT_SET(0);
      private final int value;
      private CmdCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static CmdCase valueOf(int value) {
        return forNumber(value);
      }

      public static CmdCase forNumber(int value) {
        switch (value) {
          case 101: return LOGINRESPONSE;
          case 103: return GETALLACTIVITYRESPONSE;
          case 104: return GETACTIVITYRESPONSE;
          case 105: return SCACTIVITY;
          case 0: return CMD_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public CmdCase
    getCmdCase() {
      return CmdCase.forNumber(
          cmdCase_);
    }

    public static final int LOGINRESPONSE_FIELD_NUMBER = 101;
    /**
     * <pre>
     *        Pong pong = 1;
     * </pre>
     *
     * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
     */
    public boolean hasLoginResponse() {
      return cmdCase_ == 101;
    }
    /**
     * <pre>
     *        Pong pong = 1;
     * </pre>
     *
     * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
     */
    public com.caidt.proto.ProtoDescriptor.LoginResponse getLoginResponse() {
      if (cmdCase_ == 101) {
         return (com.caidt.proto.ProtoDescriptor.LoginResponse) cmd_;
      }
      return com.caidt.proto.ProtoDescriptor.LoginResponse.getDefaultInstance();
    }
    /**
     * <pre>
     *        Pong pong = 1;
     * </pre>
     *
     * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
     */
    public com.caidt.proto.ProtoDescriptor.LoginResponseOrBuilder getLoginResponseOrBuilder() {
      if (cmdCase_ == 101) {
         return (com.caidt.proto.ProtoDescriptor.LoginResponse) cmd_;
      }
      return com.caidt.proto.ProtoDescriptor.LoginResponse.getDefaultInstance();
    }

    public static final int GETALLACTIVITYRESPONSE_FIELD_NUMBER = 103;
    /**
     * <pre>
     *        GetPlayerInfoResponse getPlayerInfoResponse = 102;
     * </pre>
     *
     * <code>optional .com.caidt.proto.GetAllActivityResponse GetAllActivityResponse = 103;</code>
     */
    public boolean hasGetAllActivityResponse() {
      return cmdCase_ == 103;
    }
    /**
     * <pre>
     *        GetPlayerInfoResponse getPlayerInfoResponse = 102;
     * </pre>
     *
     * <code>optional .com.caidt.proto.GetAllActivityResponse GetAllActivityResponse = 103;</code>
     */
    public com.caidt.proto.ProtoActivity.GetAllActivityResponse getGetAllActivityResponse() {
      if (cmdCase_ == 103) {
         return (com.caidt.proto.ProtoActivity.GetAllActivityResponse) cmd_;
      }
      return com.caidt.proto.ProtoActivity.GetAllActivityResponse.getDefaultInstance();
    }
    /**
     * <pre>
     *        GetPlayerInfoResponse getPlayerInfoResponse = 102;
     * </pre>
     *
     * <code>optional .com.caidt.proto.GetAllActivityResponse GetAllActivityResponse = 103;</code>
     */
    public com.caidt.proto.ProtoActivity.GetAllActivityResponseOrBuilder getGetAllActivityResponseOrBuilder() {
      if (cmdCase_ == 103) {
         return (com.caidt.proto.ProtoActivity.GetAllActivityResponse) cmd_;
      }
      return com.caidt.proto.ProtoActivity.GetAllActivityResponse.getDefaultInstance();
    }

    public static final int GETACTIVITYRESPONSE_FIELD_NUMBER = 104;
    /**
     * <code>optional .com.caidt.proto.GetActivityResponse getActivityResponse = 104;</code>
     */
    public boolean hasGetActivityResponse() {
      return cmdCase_ == 104;
    }
    /**
     * <code>optional .com.caidt.proto.GetActivityResponse getActivityResponse = 104;</code>
     */
    public com.caidt.proto.ProtoActivity.GetActivityResponse getGetActivityResponse() {
      if (cmdCase_ == 104) {
         return (com.caidt.proto.ProtoActivity.GetActivityResponse) cmd_;
      }
      return com.caidt.proto.ProtoActivity.GetActivityResponse.getDefaultInstance();
    }
    /**
     * <code>optional .com.caidt.proto.GetActivityResponse getActivityResponse = 104;</code>
     */
    public com.caidt.proto.ProtoActivity.GetActivityResponseOrBuilder getGetActivityResponseOrBuilder() {
      if (cmdCase_ == 104) {
         return (com.caidt.proto.ProtoActivity.GetActivityResponse) cmd_;
      }
      return com.caidt.proto.ProtoActivity.GetActivityResponse.getDefaultInstance();
    }

    public static final int SCACTIVITY_FIELD_NUMBER = 105;
    /**
     * <code>optional .com.caidt.proto.ScActivity scActivity = 105;</code>
     */
    public boolean hasScActivity() {
      return cmdCase_ == 105;
    }
    /**
     * <code>optional .com.caidt.proto.ScActivity scActivity = 105;</code>
     */
    public com.caidt.proto.ProtoActivity.ScActivity getScActivity() {
      if (cmdCase_ == 105) {
         return (com.caidt.proto.ProtoActivity.ScActivity) cmd_;
      }
      return com.caidt.proto.ProtoActivity.ScActivity.getDefaultInstance();
    }
    /**
     * <code>optional .com.caidt.proto.ScActivity scActivity = 105;</code>
     */
    public com.caidt.proto.ProtoActivity.ScActivityOrBuilder getScActivityOrBuilder() {
      if (cmdCase_ == 105) {
         return (com.caidt.proto.ProtoActivity.ScActivity) cmd_;
      }
      return com.caidt.proto.ProtoActivity.ScActivity.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasLoginResponse()) {
        if (!getLoginResponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasGetAllActivityResponse()) {
        if (!getGetAllActivityResponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasGetActivityResponse()) {
        if (!getGetActivityResponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasScActivity()) {
        if (!getScActivity().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmdCase_ == 101) {
        output.writeMessage(101, (com.caidt.proto.ProtoDescriptor.LoginResponse) cmd_);
      }
      if (cmdCase_ == 103) {
        output.writeMessage(103, (com.caidt.proto.ProtoActivity.GetAllActivityResponse) cmd_);
      }
      if (cmdCase_ == 104) {
        output.writeMessage(104, (com.caidt.proto.ProtoActivity.GetActivityResponse) cmd_);
      }
      if (cmdCase_ == 105) {
        output.writeMessage(105, (com.caidt.proto.ProtoActivity.ScActivity) cmd_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmdCase_ == 101) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(101, (com.caidt.proto.ProtoDescriptor.LoginResponse) cmd_);
      }
      if (cmdCase_ == 103) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(103, (com.caidt.proto.ProtoActivity.GetAllActivityResponse) cmd_);
      }
      if (cmdCase_ == 104) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(104, (com.caidt.proto.ProtoActivity.GetActivityResponse) cmd_);
      }
      if (cmdCase_ == 105) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(105, (com.caidt.proto.ProtoActivity.ScActivity) cmd_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.caidt.proto.ProtoScMessage.ScMessage)) {
        return super.equals(obj);
      }
      com.caidt.proto.ProtoScMessage.ScMessage other = (com.caidt.proto.ProtoScMessage.ScMessage) obj;

      boolean result = true;
      result = result && getCmdCase().equals(
          other.getCmdCase());
      if (!result) return false;
      switch (cmdCase_) {
        case 101:
          result = result && getLoginResponse()
              .equals(other.getLoginResponse());
          break;
        case 103:
          result = result && getGetAllActivityResponse()
              .equals(other.getGetAllActivityResponse());
          break;
        case 104:
          result = result && getGetActivityResponse()
              .equals(other.getGetActivityResponse());
          break;
        case 105:
          result = result && getScActivity()
              .equals(other.getScActivity());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      switch (cmdCase_) {
        case 101:
          hash = (37 * hash) + LOGINRESPONSE_FIELD_NUMBER;
          hash = (53 * hash) + getLoginResponse().hashCode();
          break;
        case 103:
          hash = (37 * hash) + GETALLACTIVITYRESPONSE_FIELD_NUMBER;
          hash = (53 * hash) + getGetAllActivityResponse().hashCode();
          break;
        case 104:
          hash = (37 * hash) + GETACTIVITYRESPONSE_FIELD_NUMBER;
          hash = (53 * hash) + getGetActivityResponse().hashCode();
          break;
        case 105:
          hash = (37 * hash) + SCACTIVITY_FIELD_NUMBER;
          hash = (53 * hash) + getScActivity().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.caidt.proto.ProtoScMessage.ScMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caidt.proto.ProtoScMessage.ScMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caidt.proto.ProtoScMessage.ScMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caidt.proto.ProtoScMessage.ScMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caidt.proto.ProtoScMessage.ScMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.caidt.proto.ProtoScMessage.ScMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.caidt.proto.ProtoScMessage.ScMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.caidt.proto.ProtoScMessage.ScMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.caidt.proto.ProtoScMessage.ScMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.caidt.proto.ProtoScMessage.ScMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.caidt.proto.ProtoScMessage.ScMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.caidt.proto.ScMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.caidt.proto.ScMessage)
        com.caidt.proto.ProtoScMessage.ScMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.caidt.proto.ProtoScMessage.internal_static_com_caidt_proto_ScMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.caidt.proto.ProtoScMessage.internal_static_com_caidt_proto_ScMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.caidt.proto.ProtoScMessage.ScMessage.class, com.caidt.proto.ProtoScMessage.ScMessage.Builder.class);
      }

      // Construct using com.caidt.proto.ProtoScMessage.ScMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        cmdCase_ = 0;
        cmd_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.caidt.proto.ProtoScMessage.internal_static_com_caidt_proto_ScMessage_descriptor;
      }

      public com.caidt.proto.ProtoScMessage.ScMessage getDefaultInstanceForType() {
        return com.caidt.proto.ProtoScMessage.ScMessage.getDefaultInstance();
      }

      public com.caidt.proto.ProtoScMessage.ScMessage build() {
        com.caidt.proto.ProtoScMessage.ScMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.caidt.proto.ProtoScMessage.ScMessage buildPartial() {
        com.caidt.proto.ProtoScMessage.ScMessage result = new com.caidt.proto.ProtoScMessage.ScMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (cmdCase_ == 101) {
          if (loginResponseBuilder_ == null) {
            result.cmd_ = cmd_;
          } else {
            result.cmd_ = loginResponseBuilder_.build();
          }
        }
        if (cmdCase_ == 103) {
          if (getAllActivityResponseBuilder_ == null) {
            result.cmd_ = cmd_;
          } else {
            result.cmd_ = getAllActivityResponseBuilder_.build();
          }
        }
        if (cmdCase_ == 104) {
          if (getActivityResponseBuilder_ == null) {
            result.cmd_ = cmd_;
          } else {
            result.cmd_ = getActivityResponseBuilder_.build();
          }
        }
        if (cmdCase_ == 105) {
          if (scActivityBuilder_ == null) {
            result.cmd_ = cmd_;
          } else {
            result.cmd_ = scActivityBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.cmdCase_ = cmdCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.caidt.proto.ProtoScMessage.ScMessage) {
          return mergeFrom((com.caidt.proto.ProtoScMessage.ScMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.caidt.proto.ProtoScMessage.ScMessage other) {
        if (other == com.caidt.proto.ProtoScMessage.ScMessage.getDefaultInstance()) return this;
        switch (other.getCmdCase()) {
          case LOGINRESPONSE: {
            mergeLoginResponse(other.getLoginResponse());
            break;
          }
          case GETALLACTIVITYRESPONSE: {
            mergeGetAllActivityResponse(other.getGetAllActivityResponse());
            break;
          }
          case GETACTIVITYRESPONSE: {
            mergeGetActivityResponse(other.getGetActivityResponse());
            break;
          }
          case SCACTIVITY: {
            mergeScActivity(other.getScActivity());
            break;
          }
          case CMD_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (hasLoginResponse()) {
          if (!getLoginResponse().isInitialized()) {
            return false;
          }
        }
        if (hasGetAllActivityResponse()) {
          if (!getGetAllActivityResponse().isInitialized()) {
            return false;
          }
        }
        if (hasGetActivityResponse()) {
          if (!getGetActivityResponse().isInitialized()) {
            return false;
          }
        }
        if (hasScActivity()) {
          if (!getScActivity().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.caidt.proto.ProtoScMessage.ScMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.caidt.proto.ProtoScMessage.ScMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int cmdCase_ = 0;
      private java.lang.Object cmd_;
      public CmdCase
          getCmdCase() {
        return CmdCase.forNumber(
            cmdCase_);
      }

      public Builder clearCmd() {
        cmdCase_ = 0;
        cmd_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilderV3<
          com.caidt.proto.ProtoDescriptor.LoginResponse, com.caidt.proto.ProtoDescriptor.LoginResponse.Builder, com.caidt.proto.ProtoDescriptor.LoginResponseOrBuilder> loginResponseBuilder_;
      /**
       * <pre>
       *        Pong pong = 1;
       * </pre>
       *
       * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
       */
      public boolean hasLoginResponse() {
        return cmdCase_ == 101;
      }
      /**
       * <pre>
       *        Pong pong = 1;
       * </pre>
       *
       * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
       */
      public com.caidt.proto.ProtoDescriptor.LoginResponse getLoginResponse() {
        if (loginResponseBuilder_ == null) {
          if (cmdCase_ == 101) {
            return (com.caidt.proto.ProtoDescriptor.LoginResponse) cmd_;
          }
          return com.caidt.proto.ProtoDescriptor.LoginResponse.getDefaultInstance();
        } else {
          if (cmdCase_ == 101) {
            return loginResponseBuilder_.getMessage();
          }
          return com.caidt.proto.ProtoDescriptor.LoginResponse.getDefaultInstance();
        }
      }
      /**
       * <pre>
       *        Pong pong = 1;
       * </pre>
       *
       * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
       */
      public Builder setLoginResponse(com.caidt.proto.ProtoDescriptor.LoginResponse value) {
        if (loginResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cmd_ = value;
          onChanged();
        } else {
          loginResponseBuilder_.setMessage(value);
        }
        cmdCase_ = 101;
        return this;
      }
      /**
       * <pre>
       *        Pong pong = 1;
       * </pre>
       *
       * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
       */
      public Builder setLoginResponse(
          com.caidt.proto.ProtoDescriptor.LoginResponse.Builder builderForValue) {
        if (loginResponseBuilder_ == null) {
          cmd_ = builderForValue.build();
          onChanged();
        } else {
          loginResponseBuilder_.setMessage(builderForValue.build());
        }
        cmdCase_ = 101;
        return this;
      }
      /**
       * <pre>
       *        Pong pong = 1;
       * </pre>
       *
       * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
       */
      public Builder mergeLoginResponse(com.caidt.proto.ProtoDescriptor.LoginResponse value) {
        if (loginResponseBuilder_ == null) {
          if (cmdCase_ == 101 &&
              cmd_ != com.caidt.proto.ProtoDescriptor.LoginResponse.getDefaultInstance()) {
            cmd_ = com.caidt.proto.ProtoDescriptor.LoginResponse.newBuilder((com.caidt.proto.ProtoDescriptor.LoginResponse) cmd_)
                .mergeFrom(value).buildPartial();
          } else {
            cmd_ = value;
          }
          onChanged();
        } else {
          if (cmdCase_ == 101) {
            loginResponseBuilder_.mergeFrom(value);
          }
          loginResponseBuilder_.setMessage(value);
        }
        cmdCase_ = 101;
        return this;
      }
      /**
       * <pre>
       *        Pong pong = 1;
       * </pre>
       *
       * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
       */
      public Builder clearLoginResponse() {
        if (loginResponseBuilder_ == null) {
          if (cmdCase_ == 101) {
            cmdCase_ = 0;
            cmd_ = null;
            onChanged();
          }
        } else {
          if (cmdCase_ == 101) {
            cmdCase_ = 0;
            cmd_ = null;
          }
          loginResponseBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *        Pong pong = 1;
       * </pre>
       *
       * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
       */
      public com.caidt.proto.ProtoDescriptor.LoginResponse.Builder getLoginResponseBuilder() {
        return getLoginResponseFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *        Pong pong = 1;
       * </pre>
       *
       * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
       */
      public com.caidt.proto.ProtoDescriptor.LoginResponseOrBuilder getLoginResponseOrBuilder() {
        if ((cmdCase_ == 101) && (loginResponseBuilder_ != null)) {
          return loginResponseBuilder_.getMessageOrBuilder();
        } else {
          if (cmdCase_ == 101) {
            return (com.caidt.proto.ProtoDescriptor.LoginResponse) cmd_;
          }
          return com.caidt.proto.ProtoDescriptor.LoginResponse.getDefaultInstance();
        }
      }
      /**
       * <pre>
       *        Pong pong = 1;
       * </pre>
       *
       * <code>optional .com.caidt.proto.LoginResponse loginResponse = 101;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.caidt.proto.ProtoDescriptor.LoginResponse, com.caidt.proto.ProtoDescriptor.LoginResponse.Builder, com.caidt.proto.ProtoDescriptor.LoginResponseOrBuilder> 
          getLoginResponseFieldBuilder() {
        if (loginResponseBuilder_ == null) {
          if (!(cmdCase_ == 101)) {
            cmd_ = com.caidt.proto.ProtoDescriptor.LoginResponse.getDefaultInstance();
          }
          loginResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.caidt.proto.ProtoDescriptor.LoginResponse, com.caidt.proto.ProtoDescriptor.LoginResponse.Builder, com.caidt.proto.ProtoDescriptor.LoginResponseOrBuilder>(
                  (com.caidt.proto.ProtoDescriptor.LoginResponse) cmd_,
                  getParentForChildren(),
                  isClean());
          cmd_ = null;
        }
        cmdCase_ = 101;
        onChanged();;
        return loginResponseBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.caidt.proto.ProtoActivity.GetAllActivityResponse, com.caidt.proto.ProtoActivity.GetAllActivityResponse.Builder, com.caidt.proto.ProtoActivity.GetAllActivityResponseOrBuilder> getAllActivityResponseBuilder_;
      /**
       * <pre>
       *        GetPlayerInfoResponse getPlayerInfoResponse = 102;
       * </pre>
       *
       * <code>optional .com.caidt.proto.GetAllActivityResponse GetAllActivityResponse = 103;</code>
       */
      public boolean hasGetAllActivityResponse() {
        return cmdCase_ == 103;
      }
      /**
       * <pre>
       *        GetPlayerInfoResponse getPlayerInfoResponse = 102;
       * </pre>
       *
       * <code>optional .com.caidt.proto.GetAllActivityResponse GetAllActivityResponse = 103;</code>
       */
      public com.caidt.proto.ProtoActivity.GetAllActivityResponse getGetAllActivityResponse() {
        if (getAllActivityResponseBuilder_ == null) {
          if (cmdCase_ == 103) {
            return (com.caidt.proto.ProtoActivity.GetAllActivityResponse) cmd_;
          }
          return com.caidt.proto.ProtoActivity.GetAllActivityResponse.getDefaultInstance();
        } else {
          if (cmdCase_ == 103) {
            return getAllActivityResponseBuilder_.getMessage();
          }
          return com.caidt.proto.ProtoActivity.GetAllActivityResponse.getDefaultInstance();
        }
      }
      /**
       * <pre>
       *        GetPlayerInfoResponse getPlayerInfoResponse = 102;
       * </pre>
       *
       * <code>optional .com.caidt.proto.GetAllActivityResponse GetAllActivityResponse = 103;</code>
       */
      public Builder setGetAllActivityResponse(com.caidt.proto.ProtoActivity.GetAllActivityResponse value) {
        if (getAllActivityResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cmd_ = value;
          onChanged();
        } else {
          getAllActivityResponseBuilder_.setMessage(value);
        }
        cmdCase_ = 103;
        return this;
      }
      /**
       * <pre>
       *        GetPlayerInfoResponse getPlayerInfoResponse = 102;
       * </pre>
       *
       * <code>optional .com.caidt.proto.GetAllActivityResponse GetAllActivityResponse = 103;</code>
       */
      public Builder setGetAllActivityResponse(
          com.caidt.proto.ProtoActivity.GetAllActivityResponse.Builder builderForValue) {
        if (getAllActivityResponseBuilder_ == null) {
          cmd_ = builderForValue.build();
          onChanged();
        } else {
          getAllActivityResponseBuilder_.setMessage(builderForValue.build());
        }
        cmdCase_ = 103;
        return this;
      }
      /**
       * <pre>
       *        GetPlayerInfoResponse getPlayerInfoResponse = 102;
       * </pre>
       *
       * <code>optional .com.caidt.proto.GetAllActivityResponse GetAllActivityResponse = 103;</code>
       */
      public Builder mergeGetAllActivityResponse(com.caidt.proto.ProtoActivity.GetAllActivityResponse value) {
        if (getAllActivityResponseBuilder_ == null) {
          if (cmdCase_ == 103 &&
              cmd_ != com.caidt.proto.ProtoActivity.GetAllActivityResponse.getDefaultInstance()) {
            cmd_ = com.caidt.proto.ProtoActivity.GetAllActivityResponse.newBuilder((com.caidt.proto.ProtoActivity.GetAllActivityResponse) cmd_)
                .mergeFrom(value).buildPartial();
          } else {
            cmd_ = value;
          }
          onChanged();
        } else {
          if (cmdCase_ == 103) {
            getAllActivityResponseBuilder_.mergeFrom(value);
          }
          getAllActivityResponseBuilder_.setMessage(value);
        }
        cmdCase_ = 103;
        return this;
      }
      /**
       * <pre>
       *        GetPlayerInfoResponse getPlayerInfoResponse = 102;
       * </pre>
       *
       * <code>optional .com.caidt.proto.GetAllActivityResponse GetAllActivityResponse = 103;</code>
       */
      public Builder clearGetAllActivityResponse() {
        if (getAllActivityResponseBuilder_ == null) {
          if (cmdCase_ == 103) {
            cmdCase_ = 0;
            cmd_ = null;
            onChanged();
          }
        } else {
          if (cmdCase_ == 103) {
            cmdCase_ = 0;
            cmd_ = null;
          }
          getAllActivityResponseBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *        GetPlayerInfoResponse getPlayerInfoResponse = 102;
       * </pre>
       *
       * <code>optional .com.caidt.proto.GetAllActivityResponse GetAllActivityResponse = 103;</code>
       */
      public com.caidt.proto.ProtoActivity.GetAllActivityResponse.Builder getGetAllActivityResponseBuilder() {
        return getGetAllActivityResponseFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *        GetPlayerInfoResponse getPlayerInfoResponse = 102;
       * </pre>
       *
       * <code>optional .com.caidt.proto.GetAllActivityResponse GetAllActivityResponse = 103;</code>
       */
      public com.caidt.proto.ProtoActivity.GetAllActivityResponseOrBuilder getGetAllActivityResponseOrBuilder() {
        if ((cmdCase_ == 103) && (getAllActivityResponseBuilder_ != null)) {
          return getAllActivityResponseBuilder_.getMessageOrBuilder();
        } else {
          if (cmdCase_ == 103) {
            return (com.caidt.proto.ProtoActivity.GetAllActivityResponse) cmd_;
          }
          return com.caidt.proto.ProtoActivity.GetAllActivityResponse.getDefaultInstance();
        }
      }
      /**
       * <pre>
       *        GetPlayerInfoResponse getPlayerInfoResponse = 102;
       * </pre>
       *
       * <code>optional .com.caidt.proto.GetAllActivityResponse GetAllActivityResponse = 103;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.caidt.proto.ProtoActivity.GetAllActivityResponse, com.caidt.proto.ProtoActivity.GetAllActivityResponse.Builder, com.caidt.proto.ProtoActivity.GetAllActivityResponseOrBuilder> 
          getGetAllActivityResponseFieldBuilder() {
        if (getAllActivityResponseBuilder_ == null) {
          if (!(cmdCase_ == 103)) {
            cmd_ = com.caidt.proto.ProtoActivity.GetAllActivityResponse.getDefaultInstance();
          }
          getAllActivityResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.caidt.proto.ProtoActivity.GetAllActivityResponse, com.caidt.proto.ProtoActivity.GetAllActivityResponse.Builder, com.caidt.proto.ProtoActivity.GetAllActivityResponseOrBuilder>(
                  (com.caidt.proto.ProtoActivity.GetAllActivityResponse) cmd_,
                  getParentForChildren(),
                  isClean());
          cmd_ = null;
        }
        cmdCase_ = 103;
        onChanged();;
        return getAllActivityResponseBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.caidt.proto.ProtoActivity.GetActivityResponse, com.caidt.proto.ProtoActivity.GetActivityResponse.Builder, com.caidt.proto.ProtoActivity.GetActivityResponseOrBuilder> getActivityResponseBuilder_;
      /**
       * <code>optional .com.caidt.proto.GetActivityResponse getActivityResponse = 104;</code>
       */
      public boolean hasGetActivityResponse() {
        return cmdCase_ == 104;
      }
      /**
       * <code>optional .com.caidt.proto.GetActivityResponse getActivityResponse = 104;</code>
       */
      public com.caidt.proto.ProtoActivity.GetActivityResponse getGetActivityResponse() {
        if (getActivityResponseBuilder_ == null) {
          if (cmdCase_ == 104) {
            return (com.caidt.proto.ProtoActivity.GetActivityResponse) cmd_;
          }
          return com.caidt.proto.ProtoActivity.GetActivityResponse.getDefaultInstance();
        } else {
          if (cmdCase_ == 104) {
            return getActivityResponseBuilder_.getMessage();
          }
          return com.caidt.proto.ProtoActivity.GetActivityResponse.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.caidt.proto.GetActivityResponse getActivityResponse = 104;</code>
       */
      public Builder setGetActivityResponse(com.caidt.proto.ProtoActivity.GetActivityResponse value) {
        if (getActivityResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cmd_ = value;
          onChanged();
        } else {
          getActivityResponseBuilder_.setMessage(value);
        }
        cmdCase_ = 104;
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.GetActivityResponse getActivityResponse = 104;</code>
       */
      public Builder setGetActivityResponse(
          com.caidt.proto.ProtoActivity.GetActivityResponse.Builder builderForValue) {
        if (getActivityResponseBuilder_ == null) {
          cmd_ = builderForValue.build();
          onChanged();
        } else {
          getActivityResponseBuilder_.setMessage(builderForValue.build());
        }
        cmdCase_ = 104;
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.GetActivityResponse getActivityResponse = 104;</code>
       */
      public Builder mergeGetActivityResponse(com.caidt.proto.ProtoActivity.GetActivityResponse value) {
        if (getActivityResponseBuilder_ == null) {
          if (cmdCase_ == 104 &&
              cmd_ != com.caidt.proto.ProtoActivity.GetActivityResponse.getDefaultInstance()) {
            cmd_ = com.caidt.proto.ProtoActivity.GetActivityResponse.newBuilder((com.caidt.proto.ProtoActivity.GetActivityResponse) cmd_)
                .mergeFrom(value).buildPartial();
          } else {
            cmd_ = value;
          }
          onChanged();
        } else {
          if (cmdCase_ == 104) {
            getActivityResponseBuilder_.mergeFrom(value);
          }
          getActivityResponseBuilder_.setMessage(value);
        }
        cmdCase_ = 104;
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.GetActivityResponse getActivityResponse = 104;</code>
       */
      public Builder clearGetActivityResponse() {
        if (getActivityResponseBuilder_ == null) {
          if (cmdCase_ == 104) {
            cmdCase_ = 0;
            cmd_ = null;
            onChanged();
          }
        } else {
          if (cmdCase_ == 104) {
            cmdCase_ = 0;
            cmd_ = null;
          }
          getActivityResponseBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.GetActivityResponse getActivityResponse = 104;</code>
       */
      public com.caidt.proto.ProtoActivity.GetActivityResponse.Builder getGetActivityResponseBuilder() {
        return getGetActivityResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.caidt.proto.GetActivityResponse getActivityResponse = 104;</code>
       */
      public com.caidt.proto.ProtoActivity.GetActivityResponseOrBuilder getGetActivityResponseOrBuilder() {
        if ((cmdCase_ == 104) && (getActivityResponseBuilder_ != null)) {
          return getActivityResponseBuilder_.getMessageOrBuilder();
        } else {
          if (cmdCase_ == 104) {
            return (com.caidt.proto.ProtoActivity.GetActivityResponse) cmd_;
          }
          return com.caidt.proto.ProtoActivity.GetActivityResponse.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.caidt.proto.GetActivityResponse getActivityResponse = 104;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.caidt.proto.ProtoActivity.GetActivityResponse, com.caidt.proto.ProtoActivity.GetActivityResponse.Builder, com.caidt.proto.ProtoActivity.GetActivityResponseOrBuilder> 
          getGetActivityResponseFieldBuilder() {
        if (getActivityResponseBuilder_ == null) {
          if (!(cmdCase_ == 104)) {
            cmd_ = com.caidt.proto.ProtoActivity.GetActivityResponse.getDefaultInstance();
          }
          getActivityResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.caidt.proto.ProtoActivity.GetActivityResponse, com.caidt.proto.ProtoActivity.GetActivityResponse.Builder, com.caidt.proto.ProtoActivity.GetActivityResponseOrBuilder>(
                  (com.caidt.proto.ProtoActivity.GetActivityResponse) cmd_,
                  getParentForChildren(),
                  isClean());
          cmd_ = null;
        }
        cmdCase_ = 104;
        onChanged();;
        return getActivityResponseBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.caidt.proto.ProtoActivity.ScActivity, com.caidt.proto.ProtoActivity.ScActivity.Builder, com.caidt.proto.ProtoActivity.ScActivityOrBuilder> scActivityBuilder_;
      /**
       * <code>optional .com.caidt.proto.ScActivity scActivity = 105;</code>
       */
      public boolean hasScActivity() {
        return cmdCase_ == 105;
      }
      /**
       * <code>optional .com.caidt.proto.ScActivity scActivity = 105;</code>
       */
      public com.caidt.proto.ProtoActivity.ScActivity getScActivity() {
        if (scActivityBuilder_ == null) {
          if (cmdCase_ == 105) {
            return (com.caidt.proto.ProtoActivity.ScActivity) cmd_;
          }
          return com.caidt.proto.ProtoActivity.ScActivity.getDefaultInstance();
        } else {
          if (cmdCase_ == 105) {
            return scActivityBuilder_.getMessage();
          }
          return com.caidt.proto.ProtoActivity.ScActivity.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.caidt.proto.ScActivity scActivity = 105;</code>
       */
      public Builder setScActivity(com.caidt.proto.ProtoActivity.ScActivity value) {
        if (scActivityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cmd_ = value;
          onChanged();
        } else {
          scActivityBuilder_.setMessage(value);
        }
        cmdCase_ = 105;
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.ScActivity scActivity = 105;</code>
       */
      public Builder setScActivity(
          com.caidt.proto.ProtoActivity.ScActivity.Builder builderForValue) {
        if (scActivityBuilder_ == null) {
          cmd_ = builderForValue.build();
          onChanged();
        } else {
          scActivityBuilder_.setMessage(builderForValue.build());
        }
        cmdCase_ = 105;
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.ScActivity scActivity = 105;</code>
       */
      public Builder mergeScActivity(com.caidt.proto.ProtoActivity.ScActivity value) {
        if (scActivityBuilder_ == null) {
          if (cmdCase_ == 105 &&
              cmd_ != com.caidt.proto.ProtoActivity.ScActivity.getDefaultInstance()) {
            cmd_ = com.caidt.proto.ProtoActivity.ScActivity.newBuilder((com.caidt.proto.ProtoActivity.ScActivity) cmd_)
                .mergeFrom(value).buildPartial();
          } else {
            cmd_ = value;
          }
          onChanged();
        } else {
          if (cmdCase_ == 105) {
            scActivityBuilder_.mergeFrom(value);
          }
          scActivityBuilder_.setMessage(value);
        }
        cmdCase_ = 105;
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.ScActivity scActivity = 105;</code>
       */
      public Builder clearScActivity() {
        if (scActivityBuilder_ == null) {
          if (cmdCase_ == 105) {
            cmdCase_ = 0;
            cmd_ = null;
            onChanged();
          }
        } else {
          if (cmdCase_ == 105) {
            cmdCase_ = 0;
            cmd_ = null;
          }
          scActivityBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .com.caidt.proto.ScActivity scActivity = 105;</code>
       */
      public com.caidt.proto.ProtoActivity.ScActivity.Builder getScActivityBuilder() {
        return getScActivityFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.caidt.proto.ScActivity scActivity = 105;</code>
       */
      public com.caidt.proto.ProtoActivity.ScActivityOrBuilder getScActivityOrBuilder() {
        if ((cmdCase_ == 105) && (scActivityBuilder_ != null)) {
          return scActivityBuilder_.getMessageOrBuilder();
        } else {
          if (cmdCase_ == 105) {
            return (com.caidt.proto.ProtoActivity.ScActivity) cmd_;
          }
          return com.caidt.proto.ProtoActivity.ScActivity.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.caidt.proto.ScActivity scActivity = 105;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.caidt.proto.ProtoActivity.ScActivity, com.caidt.proto.ProtoActivity.ScActivity.Builder, com.caidt.proto.ProtoActivity.ScActivityOrBuilder> 
          getScActivityFieldBuilder() {
        if (scActivityBuilder_ == null) {
          if (!(cmdCase_ == 105)) {
            cmd_ = com.caidt.proto.ProtoActivity.ScActivity.getDefaultInstance();
          }
          scActivityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.caidt.proto.ProtoActivity.ScActivity, com.caidt.proto.ProtoActivity.ScActivity.Builder, com.caidt.proto.ProtoActivity.ScActivityOrBuilder>(
                  (com.caidt.proto.ProtoActivity.ScActivity) cmd_,
                  getParentForChildren(),
                  isClean());
          cmd_ = null;
        }
        cmdCase_ = 105;
        onChanged();;
        return scActivityBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.caidt.proto.ScMessage)
    }

    // @@protoc_insertion_point(class_scope:com.caidt.proto.ScMessage)
    private static final com.caidt.proto.ProtoScMessage.ScMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.caidt.proto.ProtoScMessage.ScMessage();
    }

    public static com.caidt.proto.ProtoScMessage.ScMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ScMessage>
        PARSER = new com.google.protobuf.AbstractParser<ScMessage>() {
      public ScMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ScMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ScMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ScMessage> getParserForType() {
      return PARSER;
    }

    public com.caidt.proto.ProtoScMessage.ScMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_caidt_proto_ScMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_caidt_proto_ScMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026proto_sc_message.proto\022\017com.caidt.prot" +
      "o\032\026proto_descriptor.proto\032\022proto_player." +
      "proto\032\024proto_activity.proto\"\224\002\n\tScMessag" +
      "e\0227\n\rloginResponse\030e \001(\0132\036.com.caidt.pro" +
      "to.LoginResponseH\000\022I\n\026GetAllActivityResp" +
      "onse\030g \001(\0132\'.com.caidt.proto.GetAllActiv" +
      "ityResponseH\000\022C\n\023getActivityResponse\030h \001" +
      "(\0132$.com.caidt.proto.GetActivityResponse" +
      "H\000\0221\n\nscActivity\030i \001(\0132\033.com.caidt.proto" +
      ".ScActivityH\000B\005\n\003cmdJ\004\010f\020g"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.caidt.proto.ProtoDescriptor.getDescriptor(),
          com.caidt.proto.ProtoPlayer.getDescriptor(),
          com.caidt.proto.ProtoActivity.getDescriptor(),
        }, assigner);
    internal_static_com_caidt_proto_ScMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_caidt_proto_ScMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_caidt_proto_ScMessage_descriptor,
        new java.lang.String[] { "LoginResponse", "GetAllActivityResponse", "GetActivityResponse", "ScActivity", "Cmd", });
    com.caidt.proto.ProtoDescriptor.getDescriptor();
    com.caidt.proto.ProtoPlayer.getDescriptor();
    com.caidt.proto.ProtoActivity.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
